export const shivaBackgrounds = [
  require('../../assets/images/reel/reel_alpine_shrine_at_golden_dawn.webp'),
  require('../../assets/images/reel/reel_ash_sprinkled_shiva_linga_ritual.webp'),
  require('../../assets/images/reel/reel_cinematic_shiva_shrine_with_lotus_offerings.webp'),
  require('../../assets/images/reel/reel_cosmic_shiva_beneath_the_open_sky.webp'),
  require('../../assets/images/reel/reel_cosmic_shiva_beneath_the_stars.webp'),
  require('../../assets/images/reel/reel_crescent_moon_trident_shrine.webp'),
  require('../../assets/images/reel/reel_ganga_aarti_at_dusk.webp'),
  require('../../assets/images/reel/reel_himalayan_sunrise_with_sacred_trident.webp'),
  require('../../assets/images/reel/reel_lord_shiva_beneath_the_himalayan_moon_reel_shiva_quote_01.webp'),
  require('../../assets/images/reel/reel_meditating_at_the_himalayan_sunrise.webp'),
  require('../../assets/images/reel/reel_mystical_damru_beneath_shivas_moonlit_silhouette.webp'),
  require('../../assets/images/reel/reel_mystic_sadhu_beneath_moonlit_himalayas.webp'),
  require('../../assets/images/reel/reel_pilgrimage_to_the_frozen_shrine.webp'),
  require('../../assets/images/reel/reel_rudraksha_mala_at_a_shiva_shrine.webp'),
  require('../../assets/images/reel/reel_sacred_abhisheka_at_the_shiva_shrine.webp'),
  require('../../assets/images/reel/reel_shiva_and_parvati_beneath_the_himalayan_moon.webp'),
  require('../../assets/images/reel/reel_shiva_nataraja_in_cosmic_fire.webp'),
  require('../../assets/images/reel/reel_snowy_himalayan_temple_at_twilight.webp'),
  require('../../assets/images/reel/reel_somnath_temple_at_sunset.webp'),
  require('../../assets/images/reel/reel_twilight_temple_ghats_aglow.webp'),
];

export const shivaHdUrls = [
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_alpine_shrine_at_golden_dawn.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_ash_sprinkled_shiva_linga_ritual.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_cinematic_shiva_shrine_with_lotus_offerings.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_cosmic_shiva_beneath_the_open_sky.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_cosmic_shiva_beneath_the_stars.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_crescent_moon_trident_shrine.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_ganga_aarti_at_dusk.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_himalayan_sunrise_with_sacred_trident.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_lord_shiva_beneath_the_himalayan_moon_reel_shiva_quote_01.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_meditating_at_the_himalayan_sunrise.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_mystical_damru_beneath_shivas_moonlit_silhouette.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_mystic_sadhu_beneath_moonlit_himalayas.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_pilgrimage_to_the_frozen_shrine.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_rudraksha_mala_at_a_shiva_shrine.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_sacred_abhisheka_at_the_shiva_shrine.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_shiva_and_parvati_beneath_the_himalayan_moon.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_shiva_nataraja_in_cosmic_fire.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_snowy_himalayan_temple_at_twilight.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_somnath_temple_at_sunset.jpg',
  'https://mahavyomastudio.com/apps/shiv-charcha/images/wallpapers/reel_twilight_temple_ghats_aglow.jpg',
];

