export const shivaBackgrounds = [
  require('../../assets/images/reel/reel_alpine_shrine_at_golden_dawn.jpg'),
  require('../../assets/images/reel/reel_ash_sprinkled_shiva_linga_ritual.jpg'),
  require('../../assets/images/reel/reel_cinematic_shiva_shrine_with_lotus_offerings.jpg'),
  require('../../assets/images/reel/reel_cosmic_shiva_beneath_the_open_sky.jpg'),
  require('../../assets/images/reel/reel_cosmic_shiva_beneath_the_stars.jpg'),
  require('../../assets/images/reel/reel_crescent_moon_trident_shrine.jpg'),
  require('../../assets/images/reel/reel_ganga_aarti_at_dusk.jpg'),
  require('../../assets/images/reel/reel_himalayan_sunrise_with_sacred_trident.jpg'),
  require('../../assets/images/reel/reel_lord_shiva_beneath_the_himalayan_moon_reel_shiva_quote_01.jpg'),
  require('../../assets/images/reel/reel_meditating_at_the_himalayan_sunrise.jpg'),
  require('../../assets/images/reel/reel_mystical_damru_beneath_shivas_moonlit_silhouette.jpg'),
  require('../../assets/images/reel/reel_mystic_sadhu_beneath_moonlit_himalayas.jpg'),
  require('../../assets/images/reel/reel_pilgrimage_to_the_frozen_shrine.jpg'),
  require('../../assets/images/reel/reel_rudraksha_mala_at_a_shiva_shrine.jpg'),
  require('../../assets/images/reel/reel_sacred_abhisheka_at_the_shiva_shrine.jpg'),
  require('../../assets/images/reel/reel_shiva_and_parvati_beneath_the_himalayan_moon.jpg'),
  require('../../assets/images/reel/reel_shiva_nataraja_in_cosmic_fire.jpg'),
  require('../../assets/images/reel/reel_snowy_himalayan_temple_at_twilight.jpg'),
  require('../../assets/images/reel/reel_somnath_temple_at_sunset.jpg'),
  require('../../assets/images/reel/reel_twilight_temple_ghats_aglow.jpg'),
];

