import { ShivaFamilyMember, ShivaForm } from '@/types/sansar';

export const shivaFamilyMembers: ShivaFamilyMember[] = [
  {
    id: 'shiva-head',
    title: 'भगवान शिव (महादेव)',
    relation: 'पिता / जगद्गुरु',
    image: 'shiva-head',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_shiva_head.mp3',
    audioDuration: 200,
    summaryHindi:
      'देवों के देव महादेव, जो संहार और कल्याण के स्वामी हैं। वे सर्वव्यापी, आशुतोष और समस्त जीवों के परम गुरु हैं।',
    detailedText: `भगवान शिव त्रिदेवों (ब्रह्मा, विष्णु, महेश) में लय और कल्याण के अधिष्ठाता हैं। वे नटराज रूप में सृष्टि के स्पंदन, महाकाल रूप में काल चक्र और आशुतोष रूप में परम दयालु हैं। वे औघड़दानी हैं जो एक लोटा पवित्र जल और बेलपत्र से ही अपने भक्तों पर अपनी संपूर्ण कृपा बरसा देते हैं।`,
    symbols: ['त्रिशूल', 'डमरू', 'चंद्रमा', 'गंगा', 'तीसरा नेत्र', 'भस्म', 'नाग'],
    associatedFestivals: ['महाशिवरात्रि', 'सावन सोमवार', 'प्रदोष व्रत'],
  },
  {
    id: 'parvati-mother',
    title: 'माता पार्वती (जगदम्बा)',
    relation: 'माता / शिवप्रिया',
    image: 'parvati-mother',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_parvati_mother.mp3',
    audioDuration: 190,
    summaryHindi:
      'आदिशक्ति भगवती पार्वती, जो शक्ति, करुणा, वात्सल्य और गृहस्थ धर्म की पराकाष्ठा हैं।',
    detailedText: `माता पार्वती हिमवान और महारानी मेना की पुत्री हैं। उन्होंने शिवजी को पति रूप में पाने के लिए पंचाग्नि व अपर्णा तप किया। वे अन्नपूर्णा, दुर्गा, काली, गौरी और उमा रूपों में पूजित हैं। शिव और शक्ति एकात्म तत्व हैं-बिना शक्ति के शिव निश्चल हैं और बिना शिव के शक्ति गतिहीन है।`,
    symbols: ['कमल पुष्प', 'त्रिशूल', 'सिंह वाहन', 'अन्न पात्र'],
    associatedFestivals: ['हरतालिका तीज', 'नवरात्रि', 'गौरी पूजा'],
  },
  {
    id: 'ganesha-son',
    title: 'भगवान श्री गणेश',
    relation: 'प्रथम पुत्र / विघ्नहर्ता',
    image: 'ganesha-son',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_ganesha_son.mp3',
    audioDuration: 180,
    summaryHindi:
      'प्रथम पूज्य विघ्नहर्ता गणेशजी, जो बुद्धि, सिद्धि और शुभ कार्यों के दाता हैं।',
    detailedText: `माता पार्वती ने अपने चंदन उबटन से बालक गणेश की रचना की। शिवजी द्वारा गज (हाथी) का शीश लगाए जाने पर वे 'गजानन' कहलाए। माता-पिता की परिक्रमा करके उन्होंने ब्रह्मांड परिक्रमा की स्पर्धा जीती और समस्त देवों में प्रथम पूज्य होने का सर्वोच्च स्थान पाया।`,
    symbols: ['मोदक', 'परशु', 'मूषक वाहन', 'एकदंत'],
    associatedFestivals: ['गणेश चतुर्थी', 'संकष्टी चतुर्थी'],
  },
  {
    id: 'kartikeya-son',
    title: 'भगवान कार्तिकेय (स्कंद)',
    relation: 'ज्येष्ठ पुत्र / देवसेनापति',
    image: 'kartikeya-son',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_kartikeya_son.mp3',
    audioDuration: 170,
    summaryHindi:
      'देवताओं के सेनापति भगवान कार्तिकेय (मुरुगन), जिन्होंने ताड़कासुर दानव का वध किया था।',
    detailedText: `भगवान शिव के तेज से कृतिकाओं द्वारा पोषित छह मुख वाले बालक स्कंद प्रकट हुए। वे शौर्य, विजय और धर्मरक्षा के प्रतीक हैं। दक्षिण भारत में इन्हें 'मुरुगन स्वामी' और 'सुब्रमण्यम' कहा जाता है।`,
    symbols: ['वेल (भाला)', 'मयूर (मोर) वाहन'],
    associatedFestivals: ['स्कंद षष्ठी', 'थाईपुसम'],
  },
  {
    id: 'nandi-devotee',
    title: 'श्री नंदी महराज',
    relation: 'शिव वाहन / परम भक्त व गणाध्यक्ष',
    image: 'nandi-devotee',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_nandi_devotee.mp3',
    audioDuration: 160,
    summaryHindi:
      'शिवजी के परम भक्त और द्वारपाल नंदी, जिनके कान में अपनी प्रार्थना कहने पर वह शिवजी तक पहुँचती है।',
    detailedText: `महर्षि शिलाद की घोर तपस्या से अयोनिज बालक नंदी प्रकट हुए। नंदी ने नद नदी के तट पर शिवजी का ध्यान कर अमरत्व और शिवजी के वाहन व गणाध्यक्ष होने का पद पाया। प्रत्येक शिवालय में शिवलिंग के सम्मुख नंदी की प्रतिमा स्थापित होती है।`,
    symbols: ['वृषभ (बैल)', 'शिव ध्वज'],
    associatedFestivals: ['नंदी जयंती', 'प्रदोष व्रत'],
  },
  {
    id: 'ashokasundari-daughter',
    title: 'माता अशोकसुंदरी',
    relation: 'शिव-पार्वती पुत्री',
    image: 'ashokasundari-daughter',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_ashokasundari.mp3',
    audioDuration: 160,
    summaryHindi:
      'माता पार्वती के अकेलेपन को दूर करने हेतु कल्पवृक्ष से प्रकट हुई शिव-पार्वती की पावन पुत्री।',
    detailedText: `पद्म पुराण के अनुसार, माता पार्वती ने अपने अकेलेपन को दूर करने हेतु कल्पवृक्ष (इच्छा पूरी करने वाले वृक्ष) से एक सुंदर कन्या की रचना की। शोक का नाश करने के कारण उनका नाम 'अशोकसुंदरी' पड़ा। उनका विवाह नहुष राजा से हुआ। गुजरात व दक्षिण भारत में इनकी विशेष मान्यता है।`,
    symbols: ['कल्पवृक्ष', 'पद्म'],
    associatedFestivals: ['गौरी व्रत'],
  },
  {
    id: 'ayappa-son',
    title: 'भगवान अयप्पा (हरिहरपुत्र)',
    relation: 'शिव व मोहिनी (विष्णु) पुत्र',
    image: 'ayappa-son',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_ayappa.mp3',
    audioDuration: 180,
    summaryHindi:
      'केरल के सबरीमाला में पूजित शिव और मोहिनी (विष्णु) के अलौकिक पुत्र धर्मशास्ता।',
    detailedText: `महिषासुर की बहन महिषी का वध करने हेतु भगवान शिव और श्रीहरि विष्णु के मोहिनी अवतार के योग से बालशास्ता (अयप्पा) का प्राकट्य हुआ। केरल की पंपा नदी के तट पर पंडलम राजा ने उनका पालन-पोषण किया। सबरीमाला पहाड़ी पर उनका पावन धाम स्थित है।`,
    symbols: ['धनुष-बाण', 'व्याघ्र (बाघ) वाहन'],
    associatedFestivals: ['मकरविलक्कू (सबरीमाला यात्रा)'],
  },
  {
    id: 'veerabhadra-commander',
    title: 'महाबली वीरभद्र',
    relation: 'शिव जटा से प्रकट महायोद्धा',
    image: 'veerabhadra-commander',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_veerabhadra.mp3',
    audioDuration: 170,
    summaryHindi:
      'सती देह त्याग पर शिवजी की जटा से प्रकट रुद्र स्वरूप महायोद्धा जिन्होंने दक्ष यज्ञ का भंजन किया।',
    detailedText: `दक्ष द्वारा शिवजी के अनादर और माता सती के देह त्याग से क्रुद्ध होकर शिवजी ने अपनी जटा की एक लट से 1000 भुजाओं वाले भयंकर वीरभद्र को प्रकट किया। वीरभद्र ने शिवगणों के साथ कनखल में दक्ष यज्ञ का भंजन कर अधर्म का अंत किया। दक्षिण भारत में लेपाक्षी वीरभद्र मंदिर प्रसिद्ध है।`,
    symbols: ['खड्ग', 'त्रिशूल', 'मुंडमाला'],
    associatedFestivals: ['वीरभद्र जयंती'],
  },
];

export const shivaForms: ShivaForm[] = [
  {
    id: 'mahadev',
    title: 'महादेव (देवों के देव)',
    meaning: 'समस्त देवताओं में सबसे महान और परम तत्व',
    image: 'mahadev',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_mahadev.mp3',
    simpleHindi: 'सभी देवताओं में जो सबसे बड़े, सर्वशक्तिमान और करुणामय हैं, वे महादेव कहलाते हैं।',
    detailedText: 'ब्रह्माजी सृजन करते हैं, विष्णुजी पालन करते हैं और महादेव परम शांति व लय के स्वामी हैं। वे सभी देवों द्वारा पूजित होने के कारण \'महादेव\' कहलाते हैं।',
    keySymbols: ['त्रिशूल', 'चंद्रमा', 'गंगा'],
  },
  {
    id: 'neelkanth',
    title: 'नीलकंठ',
    meaning: 'समुद्र मंथन में हलाहल विष को गले में धारण करने वाले',
    image: 'neelkanth',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_neelkanth.mp3',
    simpleHindi: 'संसार को ज़हर से बचाने के लिए विष पीकर गला नीला कर लेने वाले शिवजी नीलकंठ हैं।',
    detailedText: 'जब समुद्र मंथन से विष निकला, तो जगत की रक्षा के लिए शिवजी ने उसे कंठ में रोक लिया। विष की उष्मा से कंठ नीला पड़ने पर वे \'नीलकंठ\' कहलाए।',
    keySymbols: ['नीला कंठ', 'सर्प'],
  },
  {
    id: 'nataraja',
    title: 'नटराज',
    meaning: 'आनंद तांडव और नृत्य कला के परम स्वामी',
    image: 'nataraja',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_nataraja.mp3',
    simpleHindi: 'सृष्टि के निर्माण और लय का आनंद तांडव नृत्य करने वाले शिवजी नटराज हैं।',
    detailedText: 'नटराज रूप में शिवजी का दाहिना हाथ अभय मुद्रा में, बायाँ हाथ वरद में, एक पैर अज्ञान रूपी अपस्मार पुरुष पर और चारों ओर अग्नि चक्र है जो सृष्टि चक्र को दर्शाता है।',
    keySymbols: ['डमरू', 'अग्नि वलय', 'अभय मुद्रा'],
  },
  {
    id: 'ardhanarishvara',
    title: 'अर्धनारीश्वर',
    meaning: 'शिव और शक्ति का आधा पुरुष व आधा स्त्री स्वरूप',
    image: 'ardhanarishvara',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_ardhanarishvara.mp3',
    simpleHindi: 'स्त्री और पुरुष की समानता और एकात्मता दर्शाने वाला शिव और पार्वती का मिला-जुला रूप।',
    detailedText: 'यह स्वरूप दर्शाता है कि बिना शक्ति के शिव पूर्ण नहीं हैं और बिना शिव के शक्ति गतिहीन है। दोनों मिलकर ही सृष्टि की रचना करते हैं।',
    keySymbols: ['आधा त्रिशूल', 'आधा कमल'],
  },
  {
    id: 'dakshinamurthy',
    title: 'दक्षिणामूर्ति (आदिगुरु)',
    meaning: 'दक्षिण दिशा की ओर मुख करके मौन व्याख्यान द्वारा ज्ञान देने वाले',
    image: 'dakshinamurthy',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_dakshinamurthy.mp3',
    simpleHindi: 'वटवृक्ष के नीचे मौन रहकर ऋषियों को परम तत्व का ज्ञान देने वाले शिवजी दक्षिणामूर्ति हैं।',
    detailedText: 'यह स्वरूप अध्यात्म और ज्ञान के परम गुरु का है। वे दक्षिण दिशा की ओर मुख करके विराजमान रहते हैं और शब्दविहीन मौन व्याख्यान (Silence) से संशयों का निवारण करते हैं।',
    keySymbols: ['चिन्मुद्रा', 'वटवृक्ष', 'ज्ञान पुस्तक'],
  },
  {
    id: 'kalabhairava',
    title: 'कालभैरव (काशी के कोतवाल)',
    meaning: 'काल, भय और अहंकार का मर्दन करने वाले रुद्र स्वरूप',
    image: 'kalabhairava',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_kalabhairava.mp3',
    audioDuration: 200,
    simpleHindi: 'काशी के रक्षक और समय (काल) के अधिष्ठाता जो भक्तों के भय व पापों का भस्म करते हैं।',
    detailedText: 'ब्रह्माजी के 5वें शीश के अहंकार का मर्दन करने हेतु शिवजी के नाखुन से कालभैरव प्रकट हुए। वे काशी के कोतवाल और पाप कर्मों का दंड देने वाले स्वामी हैं।',
    keySymbols: ['श्वान (कुत्ता) वाहन', 'खप्पर', 'त्रिशूल'],
  },
  {
    id: 'pashupati',
    title: 'पशुपतिनाथ',
    meaning: 'समस्त प्राणियों (पशुओं) को अज्ञान रूपी पाश से छुड़ाने वाले स्वामी',
    image: 'pashupati',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_pashupati.mp3',
    audioDuration: 190,
    simpleHindi: 'अज्ञान और माया के बंधन में बंधे जीवों (पशु) को मोक्ष प्रदान करने वाले पशुपति हैं।',
    detailedText: 'शैव सिद्धांत के अनुसार अज्ञान में बंधा जीव \'पशु\' है, माया के बंधन \'पाश\' हैं और शिवजी उन बंधनों को काटने वाले \'पति\' (पशुपति) हैं। नेपाल का पशुपतिनाथ मंदिर इसी रूप का पावन केंद्र है।',
    keySymbols: ['चतुर्मुख लिंग', 'वृषभ'],
  },
  {
    id: 'ekadasha-rudra',
    title: 'एकादश रुद्र (शिव के ११ रुद्र अवतार)',
    meaning: 'सृष्टि संरक्षण व अधर्म नाशक ११ रुद्र स्वरूप',
    image: 'ekadasha-rudra',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_ekadasha_rudra.mp3',
    audioDuration: 210,
    simpleHindi: 'कश्यप और सुरभि के पुत्र रूप में प्रकट शिवजी के 11 रुद्र जो दिशाओं और देवताओं की रक्षा करते हैं।',
    detailedText: '1. कपाली, 2. पिंगल, 3. भीम, 4. विरूपाक्ष, 5. विलोहित, 6. शास्ता, 7. अजपाद, 8. अहिर्बुध्न्य, 9. शंभु, 10. चंड, और 11. भव। ये एकादश रुद्र महाप्रलय में सृष्टि का संहार और धर्म रक्षा करते हैं।',
    keySymbols: ['11 रुद्र', 'त्रिशूल', 'अग्नि'],
  },
  {
    id: 'sharabha-avatar',
    title: 'शरभावतार (नृसिंह क्रोध शामक रूप)',
    meaning: 'सिंह और गरुड़ मिश्रित अलौकिक शिव अवतार',
    image: 'sharabha-avatar',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_sharabha.mp3',
    audioDuration: 180,
    simpleHindi: 'भगवान नृसिंह का हिरण्यकशिपु वध के बाद उग्र क्रोध शांत करने हेतु शिवजी द्वारा लिया गया शरभ पक्षी अवतार।',
    detailedText: 'जब भगवान नृसिंह ने हिरण्यकशिपु का वध किया, तो उनका क्रोधाग्नि शांत न हुआ। जगत् की रक्षा हेतु शिवजी ने 8 पैरों वाले शरभ (सिंह व गरुड़ पक्षी) रूप धारण कर नृसिंहदेव का आलिंगन कर उनका क्रोध शांत किया।',
    keySymbols: ['शरभ पक्षी पंख', 'सिंह मुख'],
  },
  {
    id: 'pippalada-avatar',
    title: 'पिप्पलाद अवतार (शनि दोष निवारक)',
    meaning: 'महर्षि दधीचि के घर अवतरित शिव अवतार',
    image: 'pippalada-avatar',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/sansar_pippalada.mp3',
    audioDuration: 170,
    simpleHindi: 'शनिदेव के कष्टों से मानव जाति की रक्षा करने वाले महर्षि पिप्पलाद रूपी शिव अवतार।',
    detailedText: 'महर्षि दधीचि के अस्थि दान के पश्चात् उनकी पत्नी सुवर्चा के गर्भ से पीपल के वृक्ष के नीचे बालक पिप्पलाद प्रकट हुए। पिप्पलाद महाराज का स्मरण करने से शनिदेव की साढ़े साती और ढैय्या का कष्ट समाप्त होता है।',
    keySymbols: ['पीपल पत्र', 'कमंडल'],
  },
];
