import { ShivaFamilyMember, ShivaForm } from '@/types/sansar';

export const shivaFamilyMembers: ShivaFamilyMember[] = [
  {
    id: 'shiva-head',
    title: 'भगवान शिव (महादेव)',
    relation: 'पिता / जगतगुरु',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    audioDuration: 200,
    summaryHindi:
      'देवों के देव महादेव, जो लय और कल्याण के स्वामी हैं। वे सर्वव्यापी, आशुतोष और समस्त जीवों के परम गुरु हैं।',
    detailedText: `शिवजी त्रिदेवों में संहार और पुनरुद्धार के अधिष्ठाता हैं। वे नटराज रूप में सृष्टि की गति और महाकाल रूप में समय के स्वामी हैं। वे औघड़दानी और परम दयालु हैं जो एक लोटा जल और बेलपत्र से ही प्रसन्न हो जाते हैं।`,
    symbols: ['त्रिशूल', 'डमरू', 'चंद्रमा', 'गंगा', 'तीसरा नेत्र', 'भस्म', 'नाग'],
    associatedFestivals: ['महाशिवरात्रि', 'सावन सोमवार', 'प्रदोष व्रत'],
  },
  {
    id: 'parvati-mother',
    title: 'माता पार्वती (जगदम्बा)',
    relation: 'माता / शिवप्रिया',
    image: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    audioDuration: 190,
    summaryHindi:
      'आदिशक्ति भगवती पार्वती, जो शक्ति, करुणा, वात्सल्य और गृहस्थ धर्म की पराकाष्ठा हैं।',
    detailedText: `माता पार्वती हिमवान और मेना की पुत्री हैं। उन्होंने शिवजी को प्राप्त करने के लिए पंचाग्नि तप किया। वे अन्नपूर्णा, दुर्गा, काली और गौरी रूपों में पूजित हैं। शिव और शक्ति एक ही सत्य के दो पहलू हैं।`,
    symbols: ['कमल पुष्प', 'त्रिशूल', 'सिंह वाहन', 'अन्न पात्र'],
    associatedFestivals: ['हरतालिका तीज', 'नवरात्रि', 'गौरी पूजा'],
  },
  {
    id: 'ganesha-son',
    title: 'भगवान श्री गणेश',
    relation: 'प्रथम पुत्र / विघ्नहर्ता',
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    audioDuration: 180,
    summaryHindi:
      'प्रथम पूज्य विघ्नहर्ता गणेशजी, जो बुद्धि, सिद्धि और शुभ कार्यों के दाता हैं।',
    detailedText: `माता पार्वती ने अपने उबटन से बालक गणेश की रचना की। शिवजी द्वारा गज (हाथी) का शीश लगाए जाने पर वे गजानन कहलाए। उन्हें प्रथम पूज्य होने का वरदान प्राप्त है।`,
    symbols: ['मोदक', 'परशु', 'मूषक वाहन', 'एकदंत'],
    associatedFestivals: ['गणेश चतुर्थी', 'संकष्टी चतुर्थी'],
  },
  {
    id: 'kartikeya-son',
    title: 'भगवान कार्तिकेय (स्कंद)',
    relation: 'ज्येष्ठ पुत्र / देवसेनापति',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    audioDuration: 170,
    summaryHindi:
      'देवताओं के सेनापति भगवान कार्तिकेय (मुरुगन), जिन्होंने ताड़कासुर दानव का वध किया था।',
    detailedText: `भगवान शिव के तेज से कृतिकाओं द्वारा पोषित छह मुख वाले बालक स्कंद प्रकट हुए। वे शौर्य, विजय और धर्मरक्षा के प्रतीक हैं। दक्षिण भारत में इन्हें 'मुरुगन स्वामी' कहा जाता है।`,
    symbols: ['वेल (भाला)', 'मयूर (मोर) वाहन'],
    associatedFestivals: ['स्कंद षष्ठी', 'थाईपुसम'],
  },
  {
    id: 'nandi-devotee',
    title: 'श्री नंदी महराज',
    relation: 'शिव वाहन / परम भक्त',
    image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    audioDuration: 160,
    summaryHindi:
      'शिवजी के परम भक्त और द्वारपाल नंदी, जिनके कान में अपनी प्रार्थना कहने पर वह शिवजी तक पहुँचती है।',
    detailedText: `महर्षि शिलाद की घोर तपस्या से नंदी प्रकट हुए। उन्होंने अमरत्व प्राप्त कर शिवजी के वाहन और गणपतियों के अधिपति होने का गौरव पाया। प्रत्येक शिवालय में शिवलिंग के सम्मुख नंदी की प्रतिमा स्थापित होती है।`,
    symbols: ['वृषभ (बैल)', 'शिव ध्वज'],
    associatedFestivals: ['नंदी जयंती', 'प्रदोष व्रत'],
  },
];

export const shivaForms: ShivaForm[] = [
  {
    id: 'mahadev',
    title: 'महादेव (देवों के देव)',
    meaning: 'समस्त देवताओं में सबसे महान और परम तत्व',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    simpleHindi: 'सभी देवताओं में जो सबसे बड़े, सर्वशक्तिमान और करुणामय हैं, वे महादेव कहलाते हैं।',
    detailedText: 'ब्रह्माजी सृजन करते हैं, विष्णुजी पालन करते हैं और महादेव परम शांति व लय के स्वामी हैं। वे सभी देवों द्वारा पूजित होने के कारण \'महादेव\' कहलाते हैं।',
    keySymbols: ['त्रिशूल', 'चंद्रमा', 'गंगा'],
  },
  {
    id: 'neelkanth',
    title: 'नीलकंठ',
    meaning: 'समुद्र मंथन में हलाहल विष को गले में धारण करने वाले',
    image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    simpleHindi: 'संसार को ज़हर से बचाने के लिए विष पीकर गला नीला कर लेने वाले शिवजी नीलकंठ हैं।',
    detailedText: 'जब समुद्र मंथन से विष निकला, तो जगत की रक्षा के लिए शिवजी ने उसे कंठ में रोक लिया। विष की उष्मा से कंठ नीला पड़ने पर वे \'नीलकंठ\' कहलाए।',
    keySymbols: ['नीला कंठ', 'सर्प'],
  },
  {
    id: 'nataraja',
    title: 'नटराज',
    meaning: 'आनंद तांडव और नृत्य कला के परम स्वामी',
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    simpleHindi: 'सृष्टि के निर्माण और लय का आनंद तांडव नृत्य करने वाले शिवजी नटराज हैं।',
    detailedText: 'नटराज रूप में शिवजी का दाहिना हाथ अभय मुद्रा में, बायाँ हाथ वरद में, एक पैर अज्ञान रूपी अपस्मार पुरुष पर और चारों ओर अग्नि चक्र है जो सृष्टि चक्र को दर्शाता है।',
    keySymbols: ['डमरू', 'अग्नि वलय', 'अभय मुद्रा'],
  },
  {
    id: 'ardhanarishvara',
    title: 'अर्धनारीश्वर',
    meaning: 'शिव और शक्ति का आधा पुरुष व आधा स्त्री स्वरूप',
    image: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    simpleHindi: 'स्त्री और पुरुष की समानता और एकात्मता दर्शाने वाला शिव और पार्वती का मिला-जुला रूप।',
    detailedText: 'यह स्वरूप दर्शाता है कि बिना शक्ति के शिव पूर्ण नहीं हैं और बिना शिव के शक्ति गतिहीन है। दोनों मिलकर ही सृष्टि की रचना करते हैं।',
    keySymbols: ['आधा त्रिशूल', 'आधा कमल'],
  },
  {
    id: 'dakshinamurthy',
    title: 'दक्षिणामूर्ति (आदिगुरु)',
    meaning: 'दक्षिण दिशा की ओर मुख करके मौन व्याख्यान द्वारा ज्ञान देने वाले',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    simpleHindi: 'वटवृक्ष के नीचे मौन रहकर ऋषियों को परम तत्व का ज्ञान देने वाले शिवजी दक्षिणामूर्ति हैं।',
    detailedText: 'यह स्वरूप अध्यात्म और ज्ञान के परम गुरु का है। वे दक्षिण दिशा की ओर मुख करके विराजमान रहते हैं और शब्दविहीन मौन व्याख्यान (Silence) से संशयों का निवारण करते हैं।',
    keySymbols: ['चिन्मुद्रा', 'वटवृक्ष', 'ज्ञान पुस्तक'],
  },
  {
    id: 'kalabhairava',
    title: 'कालभैरव (काशी के कोतवाल)',
    meaning: 'काल, भय और अहंकार का मर्दन करने वाले रुद्र स्वरूप',
    image: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    audioDuration: 200,
    simpleHindi: 'काशी के रक्षक और समय (काल) के अधिष्ठाता जो भक्तों के भय व पापों का भस्म करते हैं।',
    detailedText: 'ब्रह्माजी के 5वें शीश के अहंकार का मर्दन करने हेतु शिवजी के नाखुन से कालभैरव प्रकट हुए। वे काशी के कोतवाल और पाप कर्मों का दंड देने वाले स्वामी हैं।',
    keySymbols: ['श्वान (कुत्ता) वाहन', 'खप्पर', 'त्रिशूल'],
  },
  {
    id: 'pashupati',
    title: 'पशुपतिनाथ',
    meaning: 'समस्त प्राणियों (पशुओं) को अज्ञान रूपी पाश से छुड़ाने वाले स्वामी',
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    audioDuration: 190,
    simpleHindi: 'अज्ञान और माया के बंधन में बंधे जीवों (पशु) को मोक्ष प्रदान करने वाले पशुपति हैं।',
    detailedText: 'शैव सिद्धांत के अनुसार अज्ञान में बंधा जीव \'पशु\' है, माया के बंधन \'पाश\' हैं और शिवजी उन बंधनों को काटने वाले \'पति\' (पशुपति) हैं। नेपाल का पशुपतिनाथ मंदिर इसी रूप का पावन केंद्र है।',
    keySymbols: ['चतुर्मुख लिंग', 'वृषभ'],
  },
  {
    id: 'panchanana',
    title: 'पंचानन (पंचब्रह्म स्वरूप)',
    meaning: 'सद्योजात, वामदेव, अघोर, तत्पुरुष एवं ईशान रूपी 5 मुख',
    image: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    audioDuration: 210,
    simpleHindi: 'सृष्टि के 5 तत्वों और 5 दिशाओं का संचालन करने वाले 5 मुखों वाले शिव पंचानन हैं।',
    detailedText: '1. सद्योजात (पृथ्वी/पश्चिम), 2. वामदेव (जल/उत्तर), 3. अघोर (अग्नि/दक्षिण), 4. तत्पुरुष (वायु/पूर्व), और 5. ईशान (आकाश/ऊर्ध्व दिशा)। ये 5 मुख 5 ब्रह्मांडीय कृत्य (सृष्टि, स्थिति, संहार, तिरोभाव, अनुग्रह) का संपादन करते हैं।',
    keySymbols: ['5 मुख', '5 तत्व', '5 दिशाएँ'],
  },
  {
    id: 'mahakal',
    title: 'महाकाल',
    meaning: 'समय, काल और मृत्यु से परे परम चेतना',
    image: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?q=80&w=800&auto=format&fit=crop',
    audioUrl: 'https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3',
    simpleHindi: 'जो समय (काल) के भी स्वामी हैं और अकाल मृत्यु से रक्षा करते हैं, वे महाकाल हैं।',
    detailedText: 'उज्जैन में पूजित महाकाल स्वरूप ब्रह्मांडीय समय चक्र के नियंत्रण का प्रतीक है। जो महाकाल की शरण में आ जाता है, उसे मृत्यु का भय नहीं सताता।',
    keySymbols: ['भस्म', 'कालचक्र', 'अग्नि'],
  },
];
