import { ShaktiPeeth } from '@/types/sansar';

export const shaktiPeethas: ShaktiPeeth[] = [
  {
    id: 'kamakhya',
    title: '1. कामाख्या शक्ति पीठ',
    location: 'गुवाहाटी, नीलांचल पर्वत',
    stateRegion: 'असम',
    associatedBodyPart: 'योनि (महामुद्रा)',
    image: 'kamakhya',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_kamakhya.mp3',
    audioDuration: 210,
    latitude: 26.1664,
    longitude: 91.7064,
    traditionSource: 'कालिका पुराण एवं देवी भागवत महापुराण',
    summaryHindi: 'नीलांचल पर्वत पर स्थित सर्वोच्च तान्त्रिक शक्ति पीठ जहाँ सती का योनि भाग गिरा था। यहाँ प्रसिद्ध अम्बुबाची मेला आयोजित होता है।',
    detailedHistory: 'दक्ष यज्ञ के पश्चात् सती का योनि भाग नीलांचल पर्वत पर गिरा। यहाँ प्राकृतिक जलस्रोत से सिंचित एक शिला रूपी कुंड है। प्रतिवर्ष अम्बुबाची मेले में मंदिर 3 दिन बंद रहता है।',
  },
  {
    id: 'kalighat',
    title: '2. कालीघाट शक्ति पीठ',
    location: 'कोलकाता, हुगली नदी तट',
    stateRegion: 'पश्चिम बंगाल',
    associatedBodyPart: 'दाहिने पैर की उँगलियाँ',
    image: 'kalighat',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_kalighat.mp3',
    audioDuration: 180,
    latitude: 22.5204,
    longitude: 88.3426,
    traditionSource: 'पीठामाला तंत्र एवं पीठ निर्णय ग्रंथ',
    summaryHindi: 'कोलकाता में स्थित प्रसिद्ध सिद्धपीठ जहाँ माता सती के दाहिने चरण की उँगलियाँ गिरी थीं। भैरव नकुलेश हैं।',
    detailedHistory: 'सनातन परंपरा का अत्यंत जाग्रत केंद्र। यहाँ माँ काली के दक्षिणा रूप की स्वर्ण नेत्रों वाली प्रतिमा स्थापित है।',
  },
  {
    id: 'tarapith',
    title: '3. तारापीठ शक्ति पीठ',
    location: 'वीरभूम, द्वारका नदी तट',
    stateRegion: 'पश्चिम बंगाल',
    associatedBodyPart: 'तीसरा नेत्र (नयन)',
    image: 'tarapith',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_tarapith.mp3',
    audioDuration: 190,
    latitude: 24.1147,
    longitude: 87.7981,
    traditionSource: 'महाकाल संहिता एवं तंत्र परंपरा',
    summaryHindi: 'महाविद्या माँ तारा का महान सिद्ध पीठ जहाँ सती का तीसरा नेत्र गिरा था। वामाखेपा की तपोभूमि।',
    detailedHistory: 'तारापीठ में सती का नेत्र गिरा था। श्मशान भूमि के समीप स्थित यह पीठ महातंत्र साधना के लिए विश्वविख्यात है।',
  },
  {
    id: 'hinglaj',
    title: '4. हिंगलाज माता शक्ति पीठ',
    location: 'बलूचिस्तान (हिंगोल नदी तट)',
    stateRegion: 'पाकिस्तान / बलूचिस्तान',
    associatedBodyPart: 'ब्रह्मरंध्र (शीश)',
    image: 'hinglaj',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_hinglaj.mp3',
    audioDuration: 200,
    latitude: 25.5126,
    longitude: 65.5204,
    traditionSource: 'शिवचरित्र एवं पीठ निर्णय',
    summaryHindi: 'प्राचीन पर्वत गुफा में स्थित सिद्ध पीठ जहाँ सती का मस्तक/ब्रह्मरंध्र गिरा था। भैरव भीमलोचन हैं।',
    detailedHistory: 'हिंगोल राष्ट्रीय उद्यान में प्राकृतिक गुफा के भीतर सिंदूर लेपित सिंदूरी शिला रूप में माता हिंगलाज विराजित हैं।',
  },
  {
    id: 'jwalaji',
    title: '5. ज्वालाजी शक्ति पीठ',
    location: 'काँगड़ा valley',
    stateRegion: 'हिमाचल प्रदेश',
    associatedBodyPart: 'जिह्वा (जीभ)',
    image: 'jwalaji',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_jwalaji.mp3',
    audioDuration: 190,
    latitude: 31.8767,
    longitude: 76.3235,
    traditionSource: 'तंत्र चूड़ामणि',
    summaryHindi: 'बिना किसी ईंधन के अनादि काल से निरंतर प्रज्वलित 9 नीली ज्वालाओं का चमत्कारी पावन पीठ।',
    detailedHistory: 'सती की जिह्वा काँगड़ा की चट्टानों के बीच गिरी। यहाँ कोई मूर्ति नहीं है, प्राकृतिक ज्वाला की ही पूजा होती है।',
  },
  {
    id: 'ambaji',
    title: '6. अंबाजी शक्ति पीठ',
    location: 'बनासकांठा, गब्बर पर्वत',
    stateRegion: 'गुजरात',
    associatedBodyPart: 'हृदय भाग',
    image: 'ambaji',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_ambaji.mp3',
    audioDuration: 200,
    latitude: 24.3314,
    longitude: 72.8465,
    traditionSource: 'देवी भागवत पुराण',
    summaryHindi: 'गब्बर पहाड़ी पर सती का हृदय गिरा था। मंदिर में कोई प्रतिमा नहीं, पवित्र विशोयंत्र पूजा होती है।',
    detailedHistory: 'अरासुर पर्वतमाला पर स्थित प्राचीन पीठ जहाँ पवित्र श्रीयंत्र (विशोयंत्र) को माता के स्वरूप में पूजा जाता है।',
  },
  {
    id: 'vishalakshi',
    title: '7. मणिकर्णिका विशालाक्षी शक्ति पीठ',
    location: 'वाराणसी (काशी), मणिकर्णिका घाट',
    stateRegion: 'उत्तर प्रदेश',
    associatedBodyPart: 'मणिकर्णिका (कर्ण कुंडल)',
    image: 'vishalakshi',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_vishalakshi.mp3',
    audioDuration: 210,
    latitude: 25.3109,
    longitude: 83.0107,
    traditionSource: 'काशी खंड एवं तंत्र चूड़ामणि',
    summaryHindi: 'काशी में मणिकर्णिका घाट पर सती के कानों के कुंडल गिरे थे। यहाँ कालभैरव संरक्षक हैं।',
    detailedHistory: 'काशी विश्वनाथ के निकट स्थित जाग्रत पीठ जहाँ माता विशालाक्षी अपने विशाल करुणापूर्ण नेत्रों से भक्तों का कल्याण करती हैं।',
  },
  {
    id: 'naina-devi',
    title: '8. नैना देवी शक्ति पीठ',
    location: 'बिलासपुर, शिवालिक पहाड़ी',
    stateRegion: 'हिमाचल प्रदेश',
    associatedBodyPart: 'दोनों नेत्र',
    image: 'naina-devi',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_naina_devi.mp3',
    audioDuration: 180,
    latitude: 31.3061,
    longitude: 76.5369,
    traditionSource: 'शिव पुराण',
    summaryHindi: 'शिवालिक पर्वत पर सती के दोनों नेत्र गिरे थे। यहाँ माता नैना देवी के रूप में पूजित हैं।',
    detailedHistory: 'पहाड़ी के शिखर पर स्थित भव्य मंदिर जहाँ दो पवित्र नेत्र स्वरूपों का नित्य शृंगार व पूजन होता है।',
  },
  {
    id: 'tripura-sundari',
    title: '9. त्रिपुरा सुंदरी शक्ति पीठ',
    location: 'उदयपुर, गोमती तट',
    stateRegion: 'त्रिपुरा',
    associatedBodyPart: 'दाहिना पैर (चरण)',
    image: 'tripura-sundari',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_tripura_sundari.mp3',
    audioDuration: 220,
    latitude: 23.5332,
    longitude: 91.4912,
    traditionSource: 'पीठ निर्णय',
    summaryHindi: 'पूर्वोत्तर भारत का प्रमुख सिद्धपीठ जिसे माताबाड़ी कहा जाता है। यहाँ सती का दाहिना पाद गिरा था।',
    detailedHistory: 'कछुवे के आकार की पहाड़ी (कूर्मापृष्ठ) पर स्थित मंदिर जहाँ 500 वर्ष पुरानी कसौटी पत्थर की माता त्रिपुर सुंदरी प्रतिमा स्थापित है।',
  },
  {
    id: 'sharada-peeth',
    title: '10. शारदा शक्ति पीठ',
    location: 'नीलम घाटी (किशनगंगा तट)',
    stateRegion: 'पाक अधिकृत कश्मीर (PoK)',
    associatedBodyPart: 'दाहिना हाथ',
    image: 'sharada-peeth',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_sharada_peeth.mp3',
    audioDuration: 200,
    latitude: 34.7938,
    longitude: 73.9691,
    traditionSource: 'शारदा महात्म्य',
    summaryHindi: 'अखंड कश्मीर की अधिष्ठात्री माँ शारदा का प्राचीन ज्ञान व शक्ति पीठ जहाँ सती का दाहिना हाथ गिरा था।',
    detailedHistory: 'प्राचीन काल में यह विश्वविद्यालय व शारदा लिपि का महान केंद्र था। यहाँ सती का दाहिना हस्त गिरा था।',
  },
  {
    id: 'vaishno-devi',
    title: '11. वैष्णो देवी शक्ति पीठ',
    location: 'कटरा, त्रिकुटा पर्वत',
    stateRegion: 'जम्मू एवं कश्मीर',
    associatedBodyPart: 'दाहिनी भुजा / शीश',
    image: 'vaishno-devi',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_vaishno_devi.mp3',
    audioDuration: 240,
    latitude: 33.0308,
    longitude: 74.949,
    traditionSource: 'स्थानिक लोक परंपरा एवं तंत्र',
    summaryHindi: 'त्रिकुटा पर्वत गुफा में महाकाली, महालक्ष्मी व महासरस्वती पिंडियों के रूप में जाग्रत धाम।',
    detailedHistory: 'त्रिकुटा गुफा में माता सती की दाहिनी भुजा गिरी थी। श्रीधर पंडित व बाबा भैरवनाथ की कथा से सम्बद्ध धाम।',
  },
  {
    id: 'alopi-prayag',
    title: '12. अलोपी / प्रयाग शक्ति पीठ',
    location: 'प्रयागराज (संगम तट)',
    stateRegion: 'उत्तर प्रदेश',
    associatedBodyPart: 'हाथ की उँगलियाँ',
    image: 'alopi-prayag',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_alopi_prayag.mp3',
    audioDuration: 180,
    latitude: 25.4358,
    longitude: 81.8463,
    traditionSource: 'मत्स्य पुराण एवं तंत्र चूड़ामणि',
    summaryHindi: 'प्रयागराज संगम तट पर सती के हाथ की उँगलियाँ अदृश्य (अलोप) हो गई थीं। यहाँ अलोपी शंकरी देवी पूजित हैं।',
    detailedHistory: 'यहाँ कोई मूर्ति नहीं है, झूले के ऊपर रखे एक लकड़ी के डोले (झूले) का पूजन होता है।',
  },
  {
    id: 'vindhyavasini',
    title: '13. विन्ध्याचली शक्ति पीठ',
    location: 'मिर्ज़ापुर, विन्ध्याचल',
    stateRegion: 'उत्तर प्रदेश',
    associatedBodyPart: 'बायाँ पैर (वाम पाद)',
    image: 'vindhyavasini',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_vindhyavasini.mp3',
    audioDuration: 210,
    latitude: 25.1633,
    longitude: 82.5074,
    traditionSource: 'दुर्गा सप्तशती एवं मार्कंडेय पुराण',
    summaryHindi: 'गंगा तट विन्ध्य पर्वत पर विराजित जाग्रत पीठ। कंस के हाथ से छूटकर आकाश में प्रकट हुई योगमाया।',
    detailedHistory: 'विन्ध्याचल त्रिकोण यात्रा (विन्ध्यवासिनी, अष्टभुजा, कालीखोह) का मुख्य पावन शक्ति केंद्र।',
  },
  {
    id: 'baidyanath-jayadurga',
    title: '14. जयदुर्गा वैद्यनाथ शक्ति पीठ',
    location: 'देवघर (बाबा धाम)',
    stateRegion: 'झारखंड',
    associatedBodyPart: 'हृदय भाग',
    image: 'baidyanath-jayadurga',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_baidyanath_jayadurga.mp3',
    audioDuration: 200,
    latitude: 24.4925,
    longitude: 86.7,
    traditionSource: 'शिव महापुराण',
    summaryHindi: 'वैद्यनाथ ज्योतिर्लिंग परिसर में माता सती का हृदय गिरा था, जहाँ जयदुर्गा मंदिर स्थित है।',
    detailedHistory: 'यहाँ शिव और शक्ति एक ही परिसर में साक्षात विराजित हैं। सावन में दोनों मंदिरों के शिखरों को लाल धागे से बाँधा जाता है।',
  },
  {
    id: 'harsiddhi-ujjain',
    title: '15. हरसिद्धि (महाकाली) शक्ति पीठ',
    location: 'उज्जैन (रुद्र सागर तट)',
    stateRegion: 'मध्य प्रदेश',
    associatedBodyPart: 'कोहनी (कूर्पर)',
    image: 'harsiddhi-ujjain',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_harsiddhi_ujjain.mp3',
    audioDuration: 190,
    latitude: 23.1824,
    longitude: 75.7684,
    traditionSource: 'स्कंद पुराण (अवंती खंड)',
    summaryHindi: 'उज्जैन महाकाल के समीप स्थित पीठ जहाँ सती की कोहनी गिरी थी। राजा विक्रमादित्य की इष्टदेवी।',
    detailedHistory: 'मंदिर के प्रांगण में दो विशाल दीप स्तंभ हैं जिनमें नवरात्रि में सहस्रों दीपक प्रज्वलित किए जाते हैं।',
  },
  {
    id: 'chamundeshwari',
    title: '16. चामुंडेश्वरी शक्ति पीठ',
    location: 'मैसूर, चामुंडी पहाड़ी',
    stateRegion: 'कर्नाटक',
    associatedBodyPart: 'कान (कर्ण भाग)',
    image: 'chamundeshwari',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_chamundeshwari.mp3',
    audioDuration: 200,
    latitude: 12.2743,
    longitude: 76.6704,
    traditionSource: 'दक्षिण तंत्र परंपरा',
    summaryHindi: 'चामुंडी पहाड़ी पर स्थित दक्षिण भारत का पावन पीठ जहाँ सती के कान गिरे थे तथा महिषासुर वध हुआ था।',
    detailedHistory: 'मैसूर के वोडेयार राजवंश की कुलदेवी। दशहरे (दसरा) उत्सव के समय भव्य जूलूस का केंद्र।',
  },
  {
    id: 'kankalitala',
    title: '17. कंकालेश्वरी (कंकालीतला) शक्ति पीठ',
    location: 'बोलपुर (वीरभूम)',
    stateRegion: 'पश्चिम बंगाल',
    associatedBodyPart: 'कंकाल (अस्थि भाग)',
    image: 'kankalitala',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_kankalitala.mp3',
    audioDuration: 180,
    latitude: 23.6844,
    longitude: 87.7214,
    traditionSource: 'पीठामाला तंत्र',
    summaryHindi: 'कोपाई नदी तट पर स्थित पीठ जहाँ सती का कंकाल (अस्थि पंजर) गिरा था। पवित्र कुंड स्थित है।',
    detailedHistory: 'यहाँ मंदिर के समीप एक पवित्र कुण्ड (शिवकुण्ड) है जहाँ जल में अस्थि रूपी शिलाखंड दृश्यमान होता है।',
  },
  {
    id: 'attahasa',
    title: '18. अट्टहास शक्ति पीठ',
    location: 'लाभपुर (वीरभूम)',
    stateRegion: 'पश्चिम बंगाल',
    associatedBodyPart: 'निचला ओष्ठ (होठ)',
    image: 'attahasa',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_attahasa.mp3',
    audioDuration: 180,
    latitude: 23.829,
    longitude: 87.8093,
    traditionSource: 'पीठ निर्णय',
    summaryHindi: 'यहाँ सती का निचला होठ (ओष्ठ) गिरा था। देवी अट्टहासिनी (अट्टहास करने वाली) पूजित हैं।',
    detailedHistory: 'शांत प्राकृतिक परिवेश में स्थित पीठ जहाँ भैरव महानंद स्वामी रूप में जाने जाते हैं।',
  },
  {
    id: 'nalhati',
    title: '19. नल्हाटी शक्ति पीठ',
    location: 'नल्हाटी (वीरभूम)',
    stateRegion: 'पश्चिम बंगाल',
    associatedBodyPart: 'नली (गला/कंठ नली)',
    image: 'nalhati',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_nalhati.mp3',
    audioDuration: 175,
    latitude: 24.2982,
    longitude: 87.8398,
    traditionSource: 'तंत्र चूड़ामणि',
    summaryHindi: 'यहाँ सती की कण्ठ नली गिरी थी। नल्हाटेश्वरी देवी व योगेश भैरव का पावन धाम।',
    detailedHistory: 'छोटी पहाड़ी की तलहटी में स्थित सुंदर पीठ जहाँ सती के गले की नली का पाषाण अंश पूजित है।',
  },
  {
    id: 'bakreshwar',
    title: '20. बक्रेश्वर शक्ति पीठ',
    location: 'बक्रेश्वर (वीरभूम)',
    stateRegion: 'पश्चिम बंगाल',
    associatedBodyPart: 'मन (भ्रू मध्य)',
    image: 'bakreshwar',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_bakreshwar.mp3',
    audioDuration: 190,
    latitude: 23.8829,
    longitude: 87.3697,
    traditionSource: 'पीठ निर्णय',
    summaryHindi: 'गर्म गंधक जल स्रोतों (Hot Springs) के लिए प्रसिद्ध पीठ जहाँ सती का भ्रू मध्य भाग गिरा था।',
    detailedHistory: 'अष्टावक्र मुनि की तपोभूमि जहाँ वक्रनाथ भैरव और महिषमर्दिनी देवी विराजित हैं।',
  },
  {
    id: 'bahula',
    title: '21. बहुला शक्ति पीठ',
    location: 'केतुग्राम (बर्धमान)',
    stateRegion: 'पश्चिम बंगाल',
    associatedBodyPart: 'बायाँ हाथ (वाम बाहु)',
    image: 'bahula',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_bahula.mp3',
    audioDuration: 180,
    latitude: 23.6338,
    longitude: 88.0267,
    traditionSource: 'शिव चरित्र',
    summaryHindi: 'अजय नदी तट पर स्थित पीठ जहाँ माता सती की बायीं भुजा गिरी थी। भैरव भीरुक हैं।',
    detailedHistory: 'कार्तिक पूर्णिमा में यहाँ भव्य मेला भरता है जहाँ बहुला देवी कार्तिकेय और गणेश संग पूजित हैं।',
  },
  {
    id: 'ujjani-mangalchandi',
    title: '22. उज्जयिनी मंगलचंडी शक्ति पीठ',
    location: 'गुसकरा (बर्धमान)',
    stateRegion: 'पश्चिम बंगाल',
    associatedBodyPart: 'बायाँ कलाई',
    image: 'ujjani-mangalchandi',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_ujjani_mangalchandi.mp3',
    audioDuration: 185,
    latitude: 23.5135,
    longitude: 87.75,
    traditionSource: 'पीठ निर्णय',
    summaryHindi: 'यहाँ माता सती की बायीं कलाई (मणिबंध) गिरी थी। देवी मंगलचंडी भक्तों का कल्याण करती हैं।',
    detailedHistory: 'मंगलचंडी स्तोत्र का पाठ यहाँ अति फलदायी माना गया है। कपिलांबर भैरव रक्षक हैं।',
  },
  {
    id: 'kiriteswari',
    title: '23. किरीटेश्वरी शक्ति पीठ',
    location: 'किरीटकोण (मुर्शिदाबाद)',
    stateRegion: 'पश्चिम बंगाल',
    associatedBodyPart: 'मुकुट (किरीट)',
    image: 'kiriteswari',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_kiriteswari.mp3',
    audioDuration: 190,
    latitude: 24.1983,
    longitude: 88.2718,
    traditionSource: 'पीठ निर्णय तंत्र',
    summaryHindi: 'पश्चिम बंगाल के प्राचीनतम पीठों में से एक जहाँ सती का मुकुट (किरीट) गिरा था।',
    detailedHistory: 'बंगाल के नवाबों के काल में भी इस मंदिर की महत्ता निर्बाध रही। संवर्त भैरव यहाँ विराजित हैं।',
  },
  {
    id: 'jayanti-meghalaya',
    title: '24. जयंती शक्ति पीठ',
    location: 'जयंतिया हिल्स (नारतियांग)',
    stateRegion: 'मेघालय',
    associatedBodyPart: 'बायाँ जंघा',
    image: 'jayanti-meghalaya',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_jayanti_meghalaya.mp3',
    audioDuration: 195,
    latitude: 25.5788,
    longitude: 92.2136,
    traditionSource: 'जयंती महात्म्य',
    summaryHindi: 'जयंतिया पहाड़ियों पर सती की बायीं जाँघ गिरी थी। क्रमदीश्वर भैरव संरक्षक हैं।',
    detailedHistory: 'मेघालय के नारतियांग गाँव में 500 वर्ष पुराना पावन मंदिर जहाँ जयंतिया राजाओं की कुलदेवी पूजित हैं।',
  },
  {
    id: 'sugandha-barishal',
    title: '25. सुगंधा शक्ति पीठ',
    location: 'शिकारपुर (बरिशाल)',
    stateRegion: 'बांग्लादेश',
    associatedBodyPart: 'नासिका (नाक)',
    image: 'sugandha-barishal',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_sugandha_barishal.mp3',
    audioDuration: 190,
    latitude: 22.8465,
    longitude: 90.3124,
    traditionSource: 'तंत्र चूड़ामणि',
    summaryHindi: 'सुगंधा नदी तट पर सती की नासिका गिरी थी। देवी सुगंधा (सुनंदा) व त्र्यंबक भैरव पावन धाम।',
    detailedHistory: 'शिवचतुर्दशी पर यहाँ वृहद मेले का आयोजन होता है जहाँ सुदूर देशों से सनातन श्रद्धालु आते हैं।',
  },
  {
    id: 'chattala-sitakunda',
    title: '26. चट्टल भवानी (सीताकुंड) शक्ति पीठ',
    location: 'चंद्रनाथ पर्वत (चटगाँव)',
    stateRegion: 'बांग्लादेश',
    associatedBodyPart: 'दाहिनी भुजा',
    image: 'chattala-sitakunda',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_chattala_sitakunda.mp3',
    audioDuration: 205,
    latitude: 22.6397,
    longitude: 91.6706,
    traditionSource: 'पीठ निर्णय',
    summaryHindi: 'चंद्रनाथ पर्वत शिखर पर सती की दाहिनी बाहु गिरी थी। चंद्रशेखर भैरव यहाँ स्थित हैं।',
    detailedHistory: 'पहाड़ी चढ़ाई पर स्थित अति दुर्गम सिद्ध पीठ जहाँ प्राकृतिक गर्म जल के कुंड सीताकुंड नाम से प्रसिद्ध हैं।',
  },
  {
    id: 'yashoreswari',
    title: '27. यशोरेश्वरी शक्ति पीठ',
    location: 'ईश्वरीपुर (सतखीरा)',
    stateRegion: 'बांग्लादेश',
    associatedBodyPart: 'हथेली एवं चरण तल',
    image: 'yashoreswari',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_yashoreswari.mp3',
    audioDuration: 200,
    latitude: 22.3168,
    longitude: 89.0784,
    traditionSource: 'तंत्र शास्त्र',
    summaryHindi: 'यहाँ सती की हथेली व पाँव के तलवे गिरे थे। राजा प्रतापादित्य द्वारा निर्मित ऐतिहासिक मंदिर।',
    detailedHistory: 'चंड भैरव यहाँ संरक्षक हैं। यह पीठ बांग्लादेश के प्रमुख जाग्रत हिंदू तीर्थों में गिना जाता है।',
  },
  {
    id: 'karatoya-aparna',
    title: '28. करतोया तट अपर्णा शक्ति पीठ',
    location: 'भवानीपुर (बोगुरा)',
    stateRegion: 'बांग्लादेश',
    associatedBodyPart: 'बायाँ तल्प (पायल/तल्प)',
    image: 'karatoya-aparna',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_karatoya_aparna.mp3',
    audioDuration: 190,
    latitude: 24.606,
    longitude: 89.4447,
    traditionSource: 'शिव चरित्र',
    summaryHindi: 'करतोया नदी तट पर सती का बायाँ आभूषण तल्प गिरा था। वामन भैरव यहाँ विराजित हैं।',
    detailedHistory: 'यहाँ स्थित शंखा पोखरा तालाब में लाल चूड़ियाँ अर्पण करने की पावन लोक परंपरा है।',
  },
  {
    id: 'shreshtha-sylhet',
    title: '29. श्रीशैल महालक्ष्मी शक्ति पीठ',
    location: 'गोतागांव (सिलहट)',
    stateRegion: 'बांग्लादेश',
    associatedBodyPart: 'गला (कंठ)',
    image: 'shreshtha-sylhet',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_shreshtha_sylhet.mp3',
    audioDuration: 185,
    latitude: 24.8949,
    longitude: 91.8687,
    traditionSource: 'पीठ निर्णय',
    summaryHindi: 'सिलहट में सती का गला गिरा था। यहाँ महालक्ष्मी देवी व संबरानंद भैरव पूजित हैं।',
    detailedHistory: 'जैनपुर गाँव में स्थित इस पीठ पर नवरात्रि में विशाल चंडी पाठ का विधान है।',
  },
  {
    id: 'guhyeshwari-nepal',
    title: '30. गुह्येश्वरी शक्ति पीठ',
    location: 'काठमांडू (बागमती तट)',
    stateRegion: 'नेपाल',
    associatedBodyPart: 'दोनों घुटने (जानु द्वय)',
    image: 'guhyeshwari-nepal',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_guhyeshwari_nepal.mp3',
    audioDuration: 220,
    latitude: 27.7104,
    longitude: 85.3486,
    traditionSource: 'नेपाल महात्म्य एवं स्कंद पुराण',
    summaryHindi: 'पशुपतिनाथ मंदिर के निकट स्थित नेपाल का सर्वोच्च शक्ति पीठ जहाँ सती के दोनों घुटने गिरे थे।',
    detailedHistory: 'यहाँ कलश रूपी प्राकृतिक जल कुंड स्थित है जिसमें निरंतर पावन जल प्रवाहित रहता है। कपाली भैरव रक्षक हैं।',
  },
  {
    id: 'gandaki-muktinath',
    title: '31. गंडकी चंडी शक्ति पीठ',
    location: 'मुक्तिनाथ (गंडकी नदी उद्गम)',
    stateRegion: 'नेपाल',
    associatedBodyPart: 'मस्तक / कपोल',
    image: 'gandaki-muktinath',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_gandaki_muktinath.mp3',
    audioDuration: 210,
    latitude: 28.8167,
    longitude: 83.8718,
    traditionSource: 'तंत्र चूड़ामणि',
    summaryHindi: 'शालिग्राम शिलाओं की पावन गंडकी नदी तट पर सती का मस्तक गिरा था। चक्रपाणि भैरव धाम।',
    detailedHistory: 'मुक्तिनाथ क्षेत्र में 3710 मीटर ऊँचाई पर स्थित जहाँ 108 जलधाराएँ व ज्वाला मंदिर साक्षात हैं।',
  },
  {
    id: 'dantakali-nepal',
    title: '32. दंतकाली शक्ति पीठ',
    location: 'धरान (विजयपुर)',
    stateRegion: 'नेपाल',
    associatedBodyPart: 'दाँत (दंत पंक्तियाँ)',
    image: 'dantakali-nepal',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_dantakali_nepal.mp3',
    audioDuration: 180,
    latitude: 26.8124,
    longitude: 87.2834,
    traditionSource: 'शिव पुराण',
    summaryHindi: 'पूर्वी नेपाल की सुंदर पहाड़ियों में सती के दाँत गिरे थे। सुमेध भैरव यहाँ विराजित हैं।',
    detailedHistory: 'दंतकाली मंदिर में माता सती के दंत अवशेष रूपी शिला की पूजा बड़े श्रद्धा भाव से होती है।',
  },
  {
    id: 'manasa-kailash',
    title: '33. मानसरोवर दक्षायाणी शक्ति पीठ',
    location: 'मानसरोवर झील (कैलाश)',
    stateRegion: 'तिब्बत (चीन)',
    associatedBodyPart: 'दाहिना हथेली',
    image: 'manasa-kailash',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_manasa_kailash.mp3',
    audioDuration: 230,
    latitude: 30.6708,
    longitude: 81.4654,
    traditionSource: 'कैलाश संहिता',
    summaryHindi: 'पवित्र मानसरोवर झील के तट पर सती की दाहिनी हथेली गिरी थी। अमर भैरव संरक्षक हैं।',
    detailedHistory: 'कैलाश मानसरोवर यात्रा का परम पावन पड़ाव जहाँ हंस रूपी देवगण नित्य स्नान करते माने जाते हैं।',
  },
  {
    id: 'indrakshi-lanka',
    title: '34. इंद्राक्षी नल्लाूर शक्ति पीठ',
    location: 'जाफना (नल्लाूर)',
    stateRegion: 'श्रीलंका',
    associatedBodyPart: 'पायजेब (नूपुर)',
    image: 'indrakshi-lanka',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_indrakshi_lanka.mp3',
    audioDuration: 190,
    latitude: 9.6769,
    longitude: 80.0305,
    traditionSource: 'पीठ निर्णय तंत्र',
    summaryHindi: 'श्रीलंका के जाफना में सती के पैरों की पायल (नूपुर) गिरी थी। राक्षसेश्वर भैरव धाम।',
    detailedHistory: 'इंद्रदेव द्वारा पूजित होने के कारण इंद्राक्षी शक्तिपीठ नाम से जाना जाता है।',
  },
  {
    id: 'amarnath-mahamaya',
    title: '35. अमरनाथ महामाया शक्ति पीठ',
    location: 'अमरनाथ गुफा (पहलगाम)',
    stateRegion: 'जम्मू एवं कश्मीर',
    associatedBodyPart: 'कंठ (गला)',
    image: 'amarnath-mahamaya',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_amarnath_mahamaya.mp3',
    audioDuration: 220,
    latitude: 34.2156,
    longitude: 75.5036,
    traditionSource: 'अमरनाथ महात्म्य',
    summaryHindi: 'पवित्र अमरनाथ गुफा में बर्फानी शिवलिंग के समीप सती का गला गिरा था। महामाया देवी धाम।',
    detailedHistory: 'यहाँ त्रिसंध्येश्वर भैरव रक्षक हैं। श्रावण पूर्णिमा पर हिम शिवलिंग के साक्षात दर्शन होते हैं।',
  },
  {
    id: 'bhadrakali-kurukshetra',
    title: '36. भद्रकाली शक्ति पीठ',
    location: 'कुरुक्षेत्र (देवीकूप)',
    stateRegion: 'हरियाणा',
    associatedBodyPart: 'टखना (गुल्फ भाग)',
    image: 'bhadrakali-kurukshetra',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_bhadrakali_kurukshetra.mp3',
    audioDuration: 190,
    latitude: 29.9695,
    longitude: 76.8783,
    traditionSource: 'महाभारत एवं पीठ निर्णय',
    summaryHindi: 'यहाँ सती का दाहिना टखना गिरा था। श्री कृष्ण व पांडवों ने महाभारत युद्ध पूर्व यहाँ पूजन किया था।',
    detailedHistory: 'मनोकामना पूर्ण होने पर यहाँ पीतल के घोड़े अर्पण करने की अनूठी परंपरा है। स्थाणु भैरव संरक्षक हैं।',
  },
  {
    id: 'amba-girnar',
    title: '37. अंबा भवानी शक्ति पीठ',
    location: 'गिरनार पर्वत (जूनागढ़)',
    stateRegion: 'गुजरात',
    associatedBodyPart: 'उर (छाती)',
    image: 'amba-girnar',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_amba_girnar.mp3',
    audioDuration: 200,
    latitude: 21.5275,
    longitude: 70.529,
    traditionSource: 'स्कंद पुराण (प्रभास खंड)',
    summaryHindi: 'गिरनार पर्वत की 9996 सीढ़ियाँ चढ़कर शिखर पर स्थित पीठ जहाँ सती का उर भाग गिरा था।',
    detailedHistory: 'नवदंपति यहाँ सुखद वैवाहिक जीवन की मन्नत माँगने आते हैं। वक्रतुंड भैरव यहाँ स्थित हैं।',
  },
  {
    id: 'ambaji-patan',
    title: '38. अंबाजी पाटन शक्ति पीठ',
    location: 'पाटन (सरस्वती नदी तट)',
    stateRegion: 'गुजरात',
    associatedBodyPart: 'वाम पाद (बायाँ पैर)',
    image: 'ambaji-patan',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_ambaji_patan.mp3',
    audioDuration: 180,
    latitude: 23.8493,
    longitude: 72.1266,
    traditionSource: 'पीठ निर्णय',
    summaryHindi: 'प्राचीन पाटन नगरी में सती का बायाँ पैर गिरा था। सिद्धेश्वर भैरव यहाँ रक्षक हैं।',
    detailedHistory: 'रानी की वाव के समीप स्थित प्राचीन सिद्धपीठ जहाँ नवरात्रि में गरबा अनुष्ठान होता है।',
  },
  {
    id: 'avanti-ujjain',
    title: '39. अवंती ओष्ठ शक्ति पीठ',
    location: 'उज्जैन (भैरव पर्वत)',
    stateRegion: 'मध्य प्रदेश',
    associatedBodyPart: 'ऊपरी ओष्ठ (ऊपरी होठ)',
    image: 'avanti-ujjain',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_avanti_ujjain.mp3',
    audioDuration: 185,
    latitude: 23.1765,
    longitude: 75.7885,
    traditionSource: 'अवंती महात्म्य',
    summaryHindi: 'शिप्रा नदी के तट पर सती का ऊपरी ओष्ठ गिरा था। अवंती देवी व लंबकर्ण भैरव धाम।',
    detailedHistory: 'उज्जैन के पौराणिक अवंती क्षेत्र में स्थित पीठ जो तंत्र साधना के लिए विख्यात है।',
  },
  {
    id: 'ramgiri-chitrakoot',
    title: '40. रामगिरि शक्ति पीठ',
    location: 'चित्रकूट (मंदाकिनी तट)',
    stateRegion: 'उत्तर प्रदेश / मध्य प्रदेश',
    associatedBodyPart: 'दाहिना स्तन',
    image: 'ramgiri-chitrakoot',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_ramgiri_chitrakoot.mp3',
    audioDuration: 190,
    latitude: 25.1742,
    longitude: 80.8653,
    traditionSource: 'रामचरितमानस व पीठ निर्णय',
    summaryHindi: 'चित्रकूट पर्वत क्षेत्र में सती का दाहिना स्तन गिरा था। शिवानी देवी व चंड भैरव पावन धाम।',
    detailedHistory: 'श्री राम के 14 वर्ष वनवास काल की पावन तपोभूमि जहाँ माता सती की शक्ति साक्षात है।',
  },
  {
    id: 'panchsagar-haridwar',
    title: '41. पंचसागर शक्ति पीठ',
    location: 'हरिद्वार / वाराणसी तट',
    stateRegion: 'उत्तराखंड',
    associatedBodyPart: 'निचला दंत (दाँत)',
    image: 'panchsagar-haridwar',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_panchsagar_haridwar.mp3',
    audioDuration: 180,
    latitude: 29.9457,
    longitude: 78.1642,
    traditionSource: 'तंत्र चूड़ामणि',
    summaryHindi: 'यहाँ सती के निचले दाँत गिरे थे। देवी वाराही एवं संहार भैरव का परम सिद्ध पीठ।',
    detailedHistory: 'वाराही महाविद्या के रूप में पूजित जाग्रत शक्ति पीठ जहाँ तंत्र अनुष्ठान सिद्ध होते हैं।',
  },
  {
    id: 'kanyakumari-peeth',
    title: '42. कन्याकुमारी शक्ति पीठ',
    location: 'कन्याकुमारी (तीन समुद्र संगम)',
    stateRegion: 'तमिलनाडु',
    associatedBodyPart: 'पृष्ठ भाग (पीठ)',
    image: 'kanyakumari-peeth',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_kanyakumari_peeth.mp3',
    audioDuration: 205,
    latitude: 8.0883,
    longitude: 77.5385,
    traditionSource: 'दक्षिण महात्म्य',
    summaryHindi: 'भारत के अंतिम दक्षिणी छोर पर जहाँ तीन सागर मिलते हैं, सती की पीठ गिरी थी। भगवती बाल सुंदरी।',
    detailedHistory: 'स्वामी विवेकानंद की ध्यान शिला के सम्मुख स्थित बाल कन्या रूपी देवी का अति मनमोहक मंदिर।',
  },
  {
    id: 'bramhari-jalpaiguri',
    title: '43. भ्रामरी (त्रिश्रोता) शक्ति पीठ',
    location: 'जलपाईगुड़ी (तिस्ता नदी तट)',
    stateRegion: 'पश्चिम बंगाल',
    associatedBodyPart: 'बायाँ पैर (वाम पाद)',
    image: 'bramhari-jalpaiguri',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_bramhari_jalpaiguri.mp3',
    audioDuration: 195,
    latitude: 26.5167,
    longitude: 88.7333,
    traditionSource: 'पीठ निर्णय',
    summaryHindi: 'तिस्ता नदी तट पर सती का बायाँ पैर गिरा था। देवी भ्रामरी (भौरों की देवी) व ईश्वर भैरव धाम।',
    detailedHistory: 'जब अरूणासुर दैत्य का अत्याचार बढ़ा, तब देवी ने असंख्यों भौरों का रूप धरकर उसका संहार किया था।',
  },
  {
    id: 'kalmadhav-amarkantak',
    title: '44. कालमाधव शक्ति पीठ',
    location: 'अमरकंटक (नर्मदा उद्गम)',
    stateRegion: 'मध्य प्रदेश',
    associatedBodyPart: 'बायाँ नितंब',
    image: 'kalmadhav-amarkantak',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_kalmadhav_amarkantak.mp3',
    audioDuration: 190,
    latitude: 22.6724,
    longitude: 81.7584,
    traditionSource: 'नर्मदा पुराण',
    summaryHindi: 'सोन नदी व नर्मदा उद्गम स्थल अमरकंटक में सती का बायाँ नितंब गिरा था। काली देवी व असितांग भैरव।',
    detailedHistory: 'मैकल पर्वत शृंखला में स्थित अत्यंत सुरम्य वन प्रदेश जहाँ सिद्ध साधक निवास करते हैं।',
  },
  {
    id: 'shondesh-amarkantak',
    title: '45. शोणदेश शक्ति पीठ',
    location: 'अमरकंटक (शोणभद्र)',
    stateRegion: 'मध्य प्रदेश',
    associatedBodyPart: 'दाहिना नितंब',
    image: 'shondesh-amarkantak',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_shondesh_amarkantak.mp3',
    audioDuration: 185,
    latitude: 22.68,
    longitude: 81.76,
    traditionSource: 'पीठ निर्णय',
    summaryHindi: 'शोणभद्र नदी के उद्गम पर सती का दाहिना नितंब गिरा था। नर्मदा देवी व भद्रसेन भैरव।',
    detailedHistory: 'नर्मदा उद्गम कुंड के निकट जल धारा के रूप में प्रवाहित सिद्ध पावन धाम।',
  },
  {
    id: 'shivaharkari-karachi',
    title: '46. शिवहर्षिणी (कराची) शक्ति पीठ',
    location: 'कराची (क्लिफटन तट)',
    stateRegion: 'पाकिस्तान / सिंध',
    associatedBodyPart: 'नेत्र (आँखें)',
    image: 'shivaharkari-karachi',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_shivaharkari_karachi.mp3',
    audioDuration: 190,
    latitude: 24.8138,
    longitude: 67.0319,
    traditionSource: 'शिव चरित्र',
    summaryHindi: 'कराची समुद्र तट क्लिफटन गुफा में सती के नेत्र गिरे थे। शिवहर्षिणी देवी व क्रोधिश भैरव।',
    detailedHistory: 'समुद्र किनारे प्राकृतिक गुफा में स्थित रत्नेश्वर महादेव मंदिर परिसर का सिद्ध शक्ति केंद्र।',
  },
  {
    id: 'bhairavparvat-ujjain',
    title: '47. भैरवपर्वत शक्ति पीठ',
    location: 'शिप्रा तट (भैरवगढ़)',
    stateRegion: 'मध्य प्रदेश',
    associatedBodyPart: 'ऊपरी ओष्ठ',
    image: 'bhairavparvat-ujjain',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_bhairavparvat_ujjain.mp3',
    audioDuration: 180,
    latitude: 23.2,
    longitude: 75.77,
    traditionSource: 'अवंती तंत्र',
    summaryHindi: 'उज्जैन में शिप्रा नदी के दूसरे तट भैरवगढ़ पर सती का ऊपरी ओष्ठ अंश गिरा था। अवंती देवी।',
    detailedHistory: 'कालभैरव मंदिर के समीप स्थित प्राचीन पहाड़ी जहाँ तंत्र साधना की महान परंपरा है।',
  },
  {
    id: 'ratnavali-hooghly',
    title: '48. रत्नावली शक्ति पीठ',
    location: 'खानकुल (हुगली नदी)',
    stateRegion: 'पश्चिम बंगाल',
    associatedBodyPart: 'दाहिना कंधा (दक्षिण स्कंध)',
    image: 'ratnavali-hooghly',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_ratnavali_hooghly.mp3',
    audioDuration: 185,
    latitude: 22.7562,
    longitude: 87.8714,
    traditionSource: 'पीठ निर्णय',
    summaryHindi: 'रत्नाकर नदी तट पर सती का दाहिना कंधा गिरा था। कुमारी देवी व शिव भैरव रक्षक हैं।',
    detailedHistory: 'हुगली जिले के आनंदमयी आश्रम के निकट स्थित पावन जाग्रत पीठ।',
  },
  {
    id: 'mithila-uma',
    title: '49. मिथिला उमा शक्ति पीठ',
    location: 'जनकपुर सीमा / मधुबनी',
    stateRegion: 'नेपाल / बिहार सीमा',
    associatedBodyPart: 'बायाँ कंधा (वाम स्कंध)',
    image: 'mithila-uma',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_mithila_uma.mp3',
    audioDuration: 195,
    latitude: 26.7125,
    longitude: 85.9229,
    traditionSource: 'मिथिला महात्म्य',
    summaryHindi: 'मिथिला क्षेत्र में सती का बायाँ कंधा गिरा था। उमा देवी व महोदर भैरव पावन धाम।',
    detailedHistory: 'जनकपुर व मधुबनी की पावन भूमि जहाँ सीताजी की इष्टदेवी उमा रूप में पूजित हैं।',
  },
  {
    id: 'katyayani-vrindavan',
    title: '50. कात्यायनी वृंदावन शक्ति पीठ',
    location: 'वृंदावन (यमुना तट)',
    stateRegion: 'उत्तर प्रदेश',
    associatedBodyPart: 'केशाग्र (बालों का गुच्छा)',
    image: 'katyayani-vrindavan',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_katyayani_vrindavan.mp3',
    audioDuration: 200,
    latitude: 27.581,
    longitude: 77.7006,
    traditionSource: 'श्रीमद्भागवत महापुराण (रास पंचाध्यायी)',
    summaryHindi: 'वृंदावन में यमुना तट पर सती के बालों का गुच्छा (केशाग्र) गिरा था। कात्यायनी देवी व भूतेश भैरव।',
    detailedHistory: 'गोपियों ने श्री कृष्ण को पति रूप में पाने हेतु इसी कात्यायनी पीठ पर कात्यायनी व्रत का अनुष्ठान किया था।',
  },
  {
    id: 'shriparvat-ladakh',
    title: '51. श्रीपर्वत शक्ति पीठ',
    location: 'लद्दाख / श्रीशैलम सीमा',
    stateRegion: 'लद्दाख / आंध्र प्रदेश',
    associatedBodyPart: 'दाहिना कुंडल (कंस कान का गहना)',
    image: 'shriparvat-ladakh',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/shaktipeeth_shriparvat_ladakh.mp3',
    audioDuration: 210,
    latitude: 34.1526,
    longitude: 77.5771,
    traditionSource: 'तंत्र चूड़ामणि 51वां पीठ',
    summaryHindi: '51वां अंतिम शक्ति पीठ जहाँ सती का दाहिना कर्ण आभूषण (कुंडल) गिरा था। सुंदरी देवी व सुंदरानंद भैरव।',
    detailedHistory: 'सनातन परंपरा का 51वां पूरक पीठ जो तंत्र शास्त्रों के अनुसार 51 शक्तिपीठों की संपूर्ण परिक्रमा को सिद्ध करता है।',
  },
];
