import { ShivaFestival, ShivaSymbol, ShivaTemple } from '@/types/sansar';

export const shivaSymbols: ShivaSymbol[] = [
  {
    id: 'shivling',
    title: 'शिवलिंग (Shivling - Pillar of Light)',
    hindiName: 'शिवलिंग (निराकार ब्रह्म प्रतीक)',
    image: 'shivling',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_shivling.mp3',
    audioDuration: 200,
    simpleMeaning: 'निराकार ब्रह्म, अनंत प्रकाश स्तंभ और समस्त ब्रह्मांड की उत्पत्ति व लय का प्रतीक।',
    spiritualSignificance: 'बिना आदि और अंत का सर्वव्यापी परमात्मा जो शून्य और अनंत दोनों को समेटे है।',
    detailedText: `संस्कृत में 'लिंग' का अर्थ है 'प्रतीक' या 'चिह्न'। शिवलिंग पुरुष और प्रकृति (शिव और शक्ति) के एकात्म योग का रूप है। निचला भाग (पीठ) माता पार्वती (जलहरी) और लिंग रूप स्वयंभू महादेव हैं। यह ब्रह्मांडीय ऊर्जा स्तंभ (Jyotirlinga) को दर्शाता है जिसका न प्रारंभ है और न अंत।`,
  },
  {
    id: 'trishula',
    title: 'त्रिशूल (Trishula)',
    hindiName: 'त्रिशूल',
    image: 'trishula',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_trishula.mp3',
    audioDuration: 180,
    simpleMeaning: 'तीनों गुणों (सत्व, रज, तम) और तीनों लोकों पर महादेव के परम नियंत्रण का प्रतीक।',
    spiritualSignificance: 'सत्त्व, रजस और तमस तीनों प्रवृत्तियों का संतुलन तथा दैहिक, दैविक और भौतिक तापों का नाश।',
    detailedText: `शिवजी का त्रिशूल केवल एक अस्त्र नहीं, अपितु ब्रह्मांडीय संतुलन का प्रतीक है। इसके तीन शूल तीन नाड़ियों (इड़ा, पिंगला, सुषुम्णा), तीन काल (भूत, वर्तमान, भविष्य) और तीन गुणों (सत्व, रज, तम) को दर्शाते हैं। त्रिशूल धारण करने का अर्थ है कि महादेव इन तीनों से अतीत और इनके स्वामी हैं।`,
  },
  {
    id: 'damru',
    title: 'डमरू (Damru)',
    hindiName: 'डमरू',
    image: 'damru',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_damru.mp3',
    audioDuration: 170,
    simpleMeaning: 'सृष्टि के प्रथम नाद (शब्द/ध्वनि) और व्याकरण के चौदह माहेश्वर सूत्रों की उत्पत्ति का स्रोत।',
    spiritualSignificance: 'अक्षर ब्रह्म (ॐ) का प्रस्फुटन तथा संगीत, व्याकरण और ब्रह्मांडीय स्पंदन का प्रतीक।',
    detailedText: `शिवजी के डमरू से निकली ध्वनि 'नाद ब्रह्म' है। माना जाता है कि महर्षि पाणिनि ने शिवजी के डमरू की 14 ध्वनियों से संस्कृत व्याकरण के 'माहेश्वर सूत्र' प्राप्त किए थे। डमरू का आकार दो त्रिभुजों के मिलने जैसा है जो पदार्थ और चेतना के मिलन का प्रतीक है।`,
  },
  {
    id: 'rudraksha',
    title: 'रुद्राक्ष (Rudraksha)',
    hindiName: 'रुद्राक्ष',
    image: 'rudraksha',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_rudraksha.mp3',
    audioDuration: 190,
    simpleMeaning: 'शिवजी के अश्रु (आँसू) से उत्पन्न फल जो मन को परम शांति और सुरक्षा प्रदान करता है।',
    spiritualSignificance: 'हृदय की एकाग्रता, स्वास्थ्य लाभ और शिव कृपा प्राप्ति का पवित्र मनका।',
    detailedText: `संस्कृत में 'रुद्र' + 'अक्ष' का अर्थ है शिव के नेत्र। पौराणिक कथा के अनुसार, जब भगवान शिव ने जीवों के दुख देखकर करुणा से नयन मूँदे, तो उनके नेत्रों से अश्रु की बूंदें पृथ्वी पर गिरीं, जिनसे रुद्राक्ष के वृक्ष उत्पन्न हुए। रुद्राक्ष धारण करने से भय दूर होता है और ध्यान में गहराई आती है।`,
  },
  {
    id: 'third-eye',
    title: 'तीसरा नेत्र (Third Eye)',
    hindiName: 'तीसरा नेत्र (त्रिनेत्र)',
    image: 'third-eye',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_third_eye.mp3',
    audioDuration: 160,
    simpleMeaning: 'आध्यात्मिक अंतर्दृष्टि, अज्ञान और कामवासना के भस्म होने का प्रतीक।',
    spiritualSignificance: 'आज्ञा चक्र का जागरण और विवेक की ज्वाला से अज्ञान का नाश।',
    detailedText: `शिवजी को 'त्रिनेत्र' कहा जाता है। दो नेत्र भौतिक जगत का भान कराते हैं और तीसरा नेत्र विवेक तथा आंतरिक चेतना का प्रतीक है। जब कामदेव ने शिवजी की समाधि भंग करनी चाही, तो शिवजी ने अपना तीसरा नेत्र खोलकर कामदेव को भस्म कर दिया था।`,
  },
  {
    id: 'crescent-moon',
    title: 'चंद्रमा (Crescent Moon)',
    hindiName: 'चंद्रमा (सोम)',
    image: 'crescent-moon',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_crescent_moon.mp3',
    audioDuration: 150,
    simpleMeaning: 'मन की चंचलता पर शिवजी के पूर्ण नियंत्रण और शीतलता का प्रतीक।',
    spiritualSignificance: 'समय चक्र, मन का संयम और अमृत तुल्य शीतलता।',
    detailedText: `शिवजी के मस्तक पर विद्यमान द्वितीया का चंद्रमा मन की एकाग्रता का प्रतीक है। चंद्रमा मन का कारक है। शिवजी द्वारा चंद्रमा को जटाओं में स्थान देना यह दर्शाता है कि ज्ञानी पुरुष अपने मन को पूरी तरह वश में रखता है।`,
  },
  {
    id: 'bhasma',
    title: 'भस्म / विभूति (Bhasma)',
    hindiName: 'भस्म (विभूति)',
    image: 'bhasma',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_bhasma.mp3',
    audioDuration: 140,
    simpleMeaning: 'संसार की नश्वरता (शरीर का अंततः राख होना) और वैराग्य का सर्वोच्च प्रतीक।',
    spiritualSignificance: 'अहंकार का दाह और सर्वव्यापी पवित्रता का लेप।',
    detailedText: `शिवजी अपने सम्पूर्ण अंग पर भस्म मलते हैं। यह भस्म स्मरण कराती है कि यह नश्वर शरीर अंततः राख में बदल जाएगा। भस्म लगाने से व्यक्ति नश्वर आकर्षणों से ऊपर उठकर शाश्वत परमात्मा में ध्यान लगाता है।`,
  },
  {
    id: 'naga',
    title: 'नाग / सर्प (Vasuki)',
    hindiName: 'नाग (वासुकि)',
    image: 'naga',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_naga.mp3',
    audioDuration: 150,
    simpleMeaning: 'कुंडलिनी शक्ति के जागरण और भयमुक्ति का अलौकिक आभूषण।',
    spiritualSignificance: 'अहंकार और काल-सर्प विष पर विजय तथा कुंडलिनी जागरण।',
    detailedText: `शिवजी के गले में लिपटा नागराज वासुकि दर्शाता है कि विषैले व उपेक्षित जीवों को भी महादेव अपनी शरण में सहर्ष स्थान देते हैं। यह मानव शरीर में रीढ़ की हड्डी के मूलाधार में सुप्त कुंडलिनी ऊर्जा का भी प्रतीक है।`,
  },
];

export const famousTemples: ShivaTemple[] = [
  {
    id: 'pashupatinath',
    title: 'पशुपतिनाथ मंदिर',
    location: 'काठमांडू, वागमती नदी तट',
    region: 'नेपाल',
    image: 'pashupatinath',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_pashupatinath.mp3',
    history: 'नेपाल का सबसे पवित्र शिव मंदिर जहाँ पंचमुखी शिवलिंग पूजित है। केदारनाथ का सिर भाग यहाँ माना जाता है।',
    significance: 'समस्त प्राणियों के स्वामी (पशुपति) रूप में पूजित विश्व प्रसिद्ध धाम।',
    latitude: 27.7104,
    longitude: 85.3487,
  },
  {
    id: 'tungnath',
    title: 'तुंगनाथ मंदिर',
    location: 'रुद्रप्रयाग, चंद्रशिला पर्वत',
    region: 'उत्तराखंड',
    image: 'tungnath',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_tungnath.mp3',
    history: 'विश्व का सबसे ऊँचा शिव मंदिर (3,680 मीटर ऊँचाई पर)। पंच केदार में द्वितीय केदार जहाँ शिवजी की भुजाएँ पूजी जाती हैं।',
    significance: 'सर्वाधिक ऊँचाई पर स्थित पावन शिवालय।',
    latitude: 30.4886,
    longitude: 79.2183,
  },
  {
    id: 'amarnath',
    title: 'अमरनाथ गुफा',
    location: 'अनंतनाग, पहलगाम',
    region: 'जम्मू एवं कश्मीर',
    image: 'amarnath',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_amarnath.mp3',
    history: 'जहाँ भगवान शिव ने माता पार्वती को अमर कथा (अमरत्व का रहस्य) सुनाई थी। प्रतिवर्ष प्राकृतिक बर्फ़ का हिमशिवलिंग बनता है।',
    significance: 'अमर कथा की पावन गुफा व हिम शिवलिंग दर्शन।',
    latitude: 34.2157,
    longitude: 75.5038,
  },
];

export const shivaFestivals: ShivaFestival[] = [
  {
    id: 'mahashivratri',
    title: 'महाशिवरात्रि',
    tithiMonth: 'फाल्गुन कृष्ण चतुर्दशी',
    significance: 'शिव-पार्वती का पावन विवाहोत्सव और शिवजी के ज्योतिर्लिंग रूप का प्राकट्य दिवस।',
    image: 'mahashivratri',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_mahashivratri.mp3',
    detailedGuide: `महाशिवरात्रि का पर्व सनातन धर्म का सबसे बड़ा भक्ति पर्व है। इस दिन श्रद्धालु उपवास रखते हैं और रात्रि में चार प्रहर की विशेष पूजा करते हैं। जलाभिषेक, दूध, दही, शहद, बेलपत्र और धतूरा अर्पण करने से महादेव की असीम कृपा प्राप्त होती है।`,
    calendarDateId: 'd-mahashivratri',
  },
  {
    id: 'shravan-maas',
    title: 'सावन मास व सोमवार',
    tithiMonth: 'श्रावण मास (जुलाई - अगस्त)',
    significance: 'भगवान शिव का सबसे प्रिय मास। इस दौरान जलाभिषेक और कांवर यात्रा की महान परंपरा है।',
    image: 'shravan-maas',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_shravan_maas.mp3',
    detailedGuide: `श्रावण मास में भगवान शिव माता पार्वती के साथ पृथ्वी पर निवास करते हैं। सावन के प्रत्येक सोमवार को व्रत रखने और गंगाजल अर्पित करने से मनोकामनाएँ पूर्ण होती हैं।`,
    calendarDateId: 'd-shravan-somvar',
  },
  {
    id: 'pradosh-vrat',
    title: 'प्रदोष व्रत',
    tithiMonth: 'प्रत्येक पक्ष की त्रयोदशी तिथि (माह में दो बार)',
    significance: 'संध्या काल (प्रदोष समय) में शिवजी का आनंद तांडव और सर्व पाप मुक्ति व्रत।',
    image: 'pradosh-vrat',
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/symbol_pradosh_vrat.mp3',
    detailedGuide: `सूर्यास्त से 45 मिनट पूर्व और 45 मिनट पश्चात् का समय प्रदोष काल कहलाता है। इस समय शिवजी नंदी पर सवार होकर कैलाश पर प्रसन्न मुद्रा में नृत्य करते हैं। प्रदोष व्रत करने से दरिद्रता और क्लेश दूर होते हैं।`,
  },
];
