import { AudioItem } from '../types';

export const audioLibrary: AudioItem[] = [
  {
    id: 'a-bhajan-1',
    title: 'शिव गुरु मेरे आधार',
    subtitle: 'मधुर शिव चर्चा भजन',
    category: 'bhajans',
    duration: 345,
    audioUrl: 'https://pub-a5e262d167664d19a4543a1aeb71a9ff.r2.dev/audio/shiv_guru_mere_aadhar.mp3',
    coverImage: '',
    artist: 'शिव शिष्य मंडली',
    isPopular: true,
    lyrics: `शिव गुरु मेरे आधार, तुम बिन कौन सहारा...
हे शिव गुरु दया करो, मैं शिष्य तिहारा...
आओ चलें शिव की ओर, फैलाएं अलख सहारा...`,
  },
  {
    id: 'a-bhajan-2',
    title: 'हे शिव गुरु दया करो',
    subtitle: 'दया प्रार्थना भजन',
    category: 'bhajans',
    duration: 290,
    audioUrl: 'https://pub-a5e262d167664d19a4543a1aeb71a9ff.r2.dev/audio/he_shiv_guru_daya_karo.mp3',
    coverImage: '',
    artist: 'भक्ति स्वर तरंग',
    isPopular: true,
  },
  {
    id: 'a-mantra-108',
    title: '108 बार ॐ नमः शिवाय (मंत्र जाप)',
    subtitle: 'शांत एवं ध्यानमय मंत्र जाप',
    category: 'mantra',
    duration: 640,
    audioUrl: 'https://pub-a5e262d167664d19a4543a1aeb71a9ff.r2.dev/audio/108_om_namah_shivaya_chant.mp3',
    coverImage: '',
    artist: 'वैदिक ध्यान ध्वनि',
    isPopular: true,
  },
  {
    id: 'a-teaching-1',
    title: 'शिव शिष्यता का सरल मार्ग',
    subtitle: 'साहब श्री हरिंद्रानंद जी का दिव्य संदेश',
    category: 'teachings',
    duration: 420,
    audioUrl: 'https://pub-a5e262d167664d19a4543a1aeb71a9ff.r2.dev/audio/sahab_shri_shiv_shishyata.mp3',
    coverImage: '',
    artist: 'साहब श्री हरिंद्रानंद जी',
  },
  {
    id: 'a-charcha-song-1',
    title: 'आओ चलें शिव की ओर',
    subtitle: 'शिव चर्चा मुख्य प्रेरणा गीत',
    category: 'charcha_songs',
    duration: 310,
    audioUrl: 'https://pub-a5e262d167664d19a4543a1aeb71a9ff.r2.dev/audio/aao_chalen_shiv_ki_or.mp3',
    coverImage: '',
    artist: 'शिव परिवार',
  },
  {
    id: 'a-ambience-bell',
    title: 'मंदिर घंटी व ॐ ध्यान ध्वनि',
    subtitle: 'साधना एवं ध्यान के लिए शांतिप्रद ध्वनि',
    category: 'ambience',
    duration: 480,
    audioUrl: 'https://pub-a5e262d167664d19a4543a1aeb71a9ff.r2.dev/audio/om_meditation_ambience.mp3',
    coverImage: '',
    artist: 'शिव चर्चा भक्ति ध्वनि',
  },
];
