import { SacredDate } from '../types';

export const sacredDates: SacredDate[] = [
  {
    id: 'date-harindranand-ji',
    date: '17-09',
    title: 'साहब श्री हरिंद्रानंद जी का स्मरण दिवस',
    subtitle: 'शिव शिष्यता आंदोलन के जनक का पावन स्मरण',
    category: 'sahab_shri',
    description: 'साहब श्री हरिंद्रानंद जी ने शिव को जगतगुरु के रूप में जन-जन तक पहुँचाया और लाखों-करोड़ों लोगों को शिव से जुड़ने की प्रेरणा दी।',
    detailedText: `साहब श्री हरिंद्रानंद जी का विचार था कि शिव किसी जाति, वर्ग या सम्प्रदाय के नहीं हैं। शिव सबके हैं। 

उन्होंने तीन सरल सूत्रों (दया माँगना, चर्चा करना, 108 जाप करना) के माध्यम से एक अभूतपूर्व आध्यात्मिक जागरण की शुरुआत की। आज उनके द्वारा शुरू किया गया शिव चर्चा का यह कारवाँ देश-विदेश में करोड़ों शिष्यों को शिव गुरु से जोड़ रहा है।`,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    relatedBhajanId: 'a-bhajan-1',
  },
  {
    id: 'date-sahab-birth',
    date: '31-10',
    title: 'साहब श्री हरिंद्रानंद जी अवतरण दिवस',
    subtitle: '31 अक्टूबर 1948 - पावन जन्म जयंती',
    category: 'sahab_shri',
    description: 'साहब श्री हरिंद्रानंद जी का जन्म सिवान, बिहार के आमलोरी ग्राम में हुआ। उन्होंने सम्पूर्ण जीवन शिव शिष्यता को जन-जन तक पहुँचाने में समर्पित कर दिया।',
    detailedText: `31 अक्टूबर को शिव शिष्य मण्डली द्वारा साहब श्री का अवतरण दिवस अत्यंत श्रद्धा और उल्लास के साथ मनाया जाता है। इस दिन विशेष शिव चर्चा गोष्ठियों और वृक्षारोपण कार्यक्रमों का आयोजन किया जाता है।`,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    relatedBhajanId: 'a-bhajan-1',
  },
  {
    id: 'date-sahab-punyatithi',
    date: '04-09',
    title: 'साहब श्री हरिंद्रानंद जी महाप्रयाण दिवस',
    subtitle: '4 सितंबर 2022 - पावन स्मृति दिवस',
    category: 'sahab_shri',
    description: '4 सितंबर 2022 को साहब श्री हरिंद्रानंद जी शिव गुरु के चरणों में लीन हुए। उनकी वाणी और तीन सूत्र आज भी करोड़ों शिष्यों का मार्गदर्शन कर रहे हैं।',
    detailedText: `इस पावन अवसर पर शिव शिष्य मण्डली द्वारा संकल्प लिया जाता है कि साहब श्री के संदेश "शिव सबके गुरु हैं" को घर-घर पहुँचाया जाएगा।`,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    relatedBhajanId: 'a-bhajan-1',
  },
  {
    id: 'date-neelam-anand-ji',
    date: '25-10',
    title: 'दीदी माँ नीलम आनंद जी का पावन स्मरण दिवस',
    subtitle: 'वात्सल्य और भक्ति की प्रतिमूर्ति',
    category: 'didi_maa',
    description: 'दीदी माँ नीलम आनंद जी ने अपने मातृत्व और अगाध भक्ति से शिव चर्चा आंदोलन को हर घर तक पहुँचाने में अपना सम्पूर्ण जीवन समर्पित कर दिया।',
    detailedText: `दीदी माँ नीलम आनंद जी का जीवन शिव गुरु के प्रति पूर्ण समर्पण की प्रतिमूर्ति था। 

उनकी वाणी में ऐसा वात्सल्य और मिठास थी कि हर शिव शिष्य स्वयं को उनके निकट अनुभव करता था। उन्होंने महिलाओं और ग्रामीण क्षेत्रों के लोगों को शिव शिष्यता से जोड़ने में ऐतिहासिक योगदान दिया।`,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a8d07f.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=800&q=80',
    relatedBhajanId: 'a-bhajan-2',
  },
  {
    id: 'date-didi-birth',
    date: '27-07',
    title: 'दीदी माँ नीलम आनंद जी अवतरण दिवस',
    subtitle: '27 जुलाई - पावन जयंती एवं वृक्षारोपण पर्व',
    category: 'didi_maa',
    description: 'दीदी माँ नीलम आनंद जी का अवतरण दिवस 27 जुलाई को सम्पूर्ण शिव शिष्य परिवार द्वारा सेवा, दया और पर्यावरण संरक्षण (वृक्षारोपण) के रूप में मनाया जाता है।',
    detailedText: `दीदी माँ हमेशा प्रकृति और जीव मात्र पर दया की सीख देती थीं। उनके अवतरण दिवस पर देश-विदेश में शिव चर्चाओं के साथ-साथ हजारों पौधे लगाए जाते हैं।`,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a8d07f.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=800&q=80',
    relatedBhajanId: 'a-bhajan-2',
  },
  {
    id: 'date-didi-punyatithi',
    date: '17-06',
    title: 'दीदी माँ नीलम आनंद जी पुण्यतिथि',
    subtitle: '17 जून - मातृवत करुणा का स्मरण',
    category: 'didi_maa',
    description: '17 जून को दीदी माँ नीलम आनंद जी की पावन पुण्यतिथि पर शिव शिष्याओं द्वारा विशेष भक्ति संगीतमय शिव चर्चा का आयोजन किया जाता है।',
    detailedText: `दीदी माँ का पावन संदेश था - "शिव गुरु पर अटूट विश्वास ही जीवन की हर विपत्ति का एकमात्र समाधान है।"`,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a8d07f.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=800&q=80',
    relatedBhajanId: 'a-bhajan-2',
  },
  {
    id: 'date-mahashivratri',
    date: '08-03',
    title: 'महाशिवरात्रि पर्व',
    subtitle: 'शिव गुरु की महानतम पावन रात्रि',
    category: 'devotional',
    description: 'महाशिवरात्रि शिव और शक्ति के दिव्य मिलन का महापर्व है। इस रात्रि में 108 जाप और विशेष शिव आराधना से अपार पुण्य प्राप्त होता है।',
    detailedText: `महाशिवरात्रि की रात्रि में शिव गुरु की विशेष कृपा बरसती है। इस दिन जागरण, जाप और शिव चर्चा करने से जीवन के समस्त कष्टों का निवारण होता है।`,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=800&q=80',
    relatedBhajanId: 'a-mantra-108',
  },
  {
    id: 'date-pradosh-vrat',
    date: '13-09',
    title: 'प्रदोष व्रत (त्रयोदशी)',
    subtitle: 'शिव संध्या पूजा का पावन समय',
    category: 'devotional',
    description: 'प्रत्येक मास की त्रयोदशी तिथि को प्रदोष व्रत मनाया जाता है। संध्या काल (सूर्यास्त समय) में शिव आराधना विशेष फलदायी होती है।',
    detailedText: `प्रदोष काल में शिव गुरु कैलाश पर्वत पर प्रसन्नचित्त मुद्रा में नृत्य करते हैं। इस समय दया माँगने और नमः शिवाय का जाप करने से पापों का क्षय होता है।`,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=800&q=80',
    relatedBhajanId: 'a-mantra-108',
  },
  {
    id: 'date-masik-shivratri',
    date: '14-09',
    title: 'मासिक शिवरात्रि (चतुर्दशी)',
    subtitle: 'मासिक शिव साधना व 108 जाप पर्व',
    category: 'devotional',
    description: 'कृष्ण पक्ष की चतुर्दशी तिथि को मासिक शिवरात्रि मनाई जाती है। यह रात्रि साधना के लिए अत्यंत फलदायी है।',
    detailedText: `हर माह की शिवरात्रि पर शिव गुरु के चरणों में विशेष दया माँगी जाती है और 108 मणके जाप द्वारा गुरु नमन अर्पित किया जाता है।`,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=800&q=80',
    relatedBhajanId: 'a-mantra-108',
  },
  {
    id: 'date-shravan-maas',
    date: '22-07',
    title: 'पावन श्रावण मास प्रारम्भ',
    subtitle: 'शिव भक्ति का सर्वोपरि पावन माह',
    category: 'devotional',
    description: 'श्रावण मास में शिव गुरु की विशेष आराधना, जलाभिषेक और शिव चर्चा गोष्ठियों का आयोजन किया जाता है।',
    detailedText: `श्रावण मास में पूरे भारतवर्ष और विश्व में शिव शिष्य मण्डली द्वारा विशेष दया माँगने के कार्यक्रम और विशाल शिव चर्चाएँ आयोजित की जाती हैं।`,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a8d07f.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    relatedBhajanId: 'a-bhajan-1',
  },
  {
    id: 'date-nag-panchami',
    date: '09-08',
    title: 'नाग पंचमी पर्व',
    subtitle: 'शिव के कण्ठहार नाग वासुकी पूजन',
    category: 'devotional',
    description: 'श्रावण शुक्ल पंचमी को नाग पंचमी मनाई जाती है। इस दिन महादेव के गले में सुशोभित नागराज वासुकी की पूजा की जाती है।',
    detailedText: `नाग पंचमी के दिन शिव मंदिर में दुग्धाभिषेक और नमः शिवाय का जाप करने से सर्प दोष एवं भय से मुक्ति मिलती है।`,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=800&q=80',
    relatedBhajanId: 'a-mantra-108',
  },
  {
    id: 'date-kartik-purnima',
    date: '15-11',
    title: 'कार्तिक पूर्णिमा (त्रिपुरारी पूर्णिमा)',
    subtitle: 'देव दीपावली एवं शिव विजय पर्व',
    category: 'devotional',
    description: 'कार्तिक पूर्णिमा को त्रिपुरारी पूर्णिमा भी कहा जाता है। इस दिन महादेव ने त्रिपुरासुर का वध कर देवताओं को भयमुक्त किया था।',
    detailedText: `इस रात्रि में दीपदान, 108 मणके जाप और शिव चर्चा करने से अपार सुख, समृद्धि और आत्मिक बल प्राप्त होता है।`,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
    imageUrl: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=800&q=80',
    relatedBhajanId: 'a-bhajan-1',
  },
];

