import { AudioItem } from '../types';

export interface PravachanItem extends AudioItem {
  speaker: 'sahab_shri' | 'didi_maa' | 'devotional_singer';
  speechContext?: string;
}

export const pravachanLibrary: PravachanItem[] = [
  {
    id: 'pr-sahab-1',
    title: 'शिव गुरु सब जीवों के हैं',
    subtitle: 'साहब श्री हरिंद्रानंद जी का पावन अमृत वचन',
    category: 'teachings',
    speaker: 'sahab_shri',
    artist: 'साहब श्री हरिंद्रानंद जी',
    duration: 420,
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/pravachan_sahab_shri_01.mp3',
    coverImage: '',
    speechContext: 'शिव शिष्यता के तीन सूत्रों की व्याख्या और गुरु शिव का स्वरूप।',
    isPopular: true,
  },
  {
    id: 'pr-didi-1',
    title: 'दया माँगने का सच्चा अर्थ',
    subtitle: 'दीदी माँ नीलम आनंद जी का संदेश',
    category: 'teachings',
    speaker: 'didi_maa',
    artist: 'दीदी माँ नीलम आनंद जी',
    duration: 360,
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/pravachan_didi_maa_01.mp3',
    coverImage: '',
    speechContext: 'गुरु शिव से दया माँगते समय मन का समर्पण कैसे हो।',
    isPopular: true,
  },
  {
    id: 'pr-sahab-2',
    title: 'चर्चा करने से गुरु कृपा का अनुभव',
    subtitle: 'द्वितीय सूत्र की गहन व्याख्या',
    category: 'teachings',
    speaker: 'sahab_shri',
    artist: 'साहब श्री हरिंद्रानंद जी',
    duration: 510,
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/pravachan_sahab_shri_02.mp3',
    coverImage: '',
    speechContext: 'जब दो लोग शिव गुरु की बात करते हैं तो वहाँ शिव उपस्थित रहते हैं।',
    isPopular: true,
  },
  {
    id: 'pr-didi-2',
    title: 'मातृवत करुणा और शिव साधना',
    subtitle: 'दीदी माँ का पावन प्रवचन',
    category: 'teachings',
    speaker: 'didi_maa',
    artist: 'दीदी माँ नीलम आनंद जी',
    duration: 390,
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/pravachan_didi_maa_02.mp3',
    coverImage: '',
    speechContext: 'माताओं व बहनों के लिए शिव गुरु से जुड़ने का सरल मार्ग।',
  },
  {
    id: 'pr-mantra-108',
    title: '108 नमः शिवाय मणके जाप ध्वनि',
    subtitle: 'मार्गदर्शित ध्यान व जाप ध्वनि',
    category: 'mantra',
    speaker: 'devotional_singer',
    artist: 'शिव चर्चा साधना',
    duration: 600,
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/108_om_namah_shivaya_chant.mp3',
    coverImage: '',
    isPopular: true,
  },
  {
    id: 'pr-bhajan-1',
    title: 'हे शिव गुरु दया कर दो',
    subtitle: 'मधुर शिव चर्चा भजन',
    category: 'charcha_songs',
    speaker: 'devotional_singer',
    artist: 'शिव शिष्य भजन मण्डली',
    duration: 320,
    audioUrl: 'https://mahavyomastudio.com/apps/shiv-charcha/audio/he_shiv_guru_daya_karo.mp3',
    coverImage: '',
    isPopular: true,
  },
];
