import { AudioItem } from '../types';

export interface PravachanItem extends AudioItem {
  speaker: 'sahab_shri' | 'didi_maa' | 'devotional_singer';
  speechContext?: string;
}

export const pravachanLibrary: PravachanItem[] = [
  {
    id: 'pr-sahab-1',
    title: 'शिव गुरु सब जीवों के हैं',
    subtitle: 'साहब श्री हरिंद्रानंद जी का पावन अमृत वचन',
    category: 'teachings',
    speaker: 'sahab_shri',
    artist: 'साहब श्री हरिंद्रानंद जी',
    duration: 420,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
    coverImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    speechContext: 'शिव शिष्यता के तीन सूत्रों की व्याख्या और गुरु शिव का स्वरूप।',
    isPopular: true,
  },
  {
    id: 'pr-didi-1',
    title: 'दया माँगने का सच्चा अर्थ',
    subtitle: 'दीदी माँ नीलम आनंद जी का संदेश',
    category: 'teachings',
    speaker: 'didi_maa',
    artist: 'दीदी माँ नीलम आनंद जी',
    duration: 360,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a8d07f.mp3',
    coverImage: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=800&q=80',
    speechContext: 'गुरु शिव से दया माँगते समय मन का समर्पण कैसे हो।',
    isPopular: true,
  },
  {
    id: 'pr-sahab-2',
    title: 'चर्चा करने से गुरु कृपा का अनुभव',
    subtitle: 'द्वितीय सूत्र की गहन व्याख्या',
    category: 'teachings',
    speaker: 'sahab_shri',
    artist: 'साहब श्री हरिंद्रानंद जी',
    duration: 510,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3',
    coverImage: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=800&q=80',
    speechContext: 'जब दो लोग शिव गुरु की बात करते हैं तो वहाँ शिव उपस्थित रहते हैं।',
    isPopular: true,
  },
  {
    id: 'pr-didi-2',
    title: 'मातृवत करुणा और शिव साधना',
    subtitle: 'दीदी माँ का पावन प्रवचन',
    category: 'teachings',
    speaker: 'didi_maa',
    artist: 'दीदी माँ नीलम आनंद जी',
    duration: 390,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a8d07f.mp3',
    coverImage: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=800&q=80',
    speechContext: 'माताओं व बहनों के लिए शिव गुरु से जुड़ने का सरल मार्ग।',
  },
  {
    id: 'pr-mantra-108',
    title: '108 नमः शिवाय मणके जाप ध्वनि',
    subtitle: 'मार्गदर्शित ध्यान व जाप ध्वनि',
    category: 'mantra',
    speaker: 'devotional_singer',
    artist: 'शिव चर्चा साधना',
    duration: 600,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
    coverImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    isPopular: true,
  },
  {
    id: 'pr-bhajan-1',
    title: 'हे शिव गुरु दया कर दो',
    subtitle: 'मधुर शिव चर्चा भजन',
    category: 'charcha_songs',
    speaker: 'devotional_singer',
    artist: 'शिव शिष्य भजन मण्डली',
    duration: 320,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3',
    coverImage: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=800&q=80',
    isPopular: true,
  },
];
