import { ShareTemplate } from '../types';

export const shareTemplates: ShareTemplate[] = [
  {
    id: 'st-maroon-gold',
    title: 'शाही मरून (Royal Maroon)',
    category: 'shiv_guru',
    style: 'traditional',
    bgGradient: ['#4A0E17', '#1A0006'],
    textColor: '#FFFDF7',
    accentColor: '#F5D061',
    borderStyle: 'gold_ornate',
    defaultText: 'शिव ही गुरु हैं, गुरु ही शिव हैं। आओ चलें शिव की ओर! 🌺',
    defaultAuthor: '- साहब श्री हरिंद्रानंद जी',
    iconName: 'sparkles',
    artworkUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'st-saffron-classic',
    title: 'पावन केसरिया (Sacred Saffron)',
    category: 'daily',
    style: 'minimal',
    bgGradient: ['#E65100', '#992400'],
    textColor: '#FFFFFF',
    accentColor: '#FFD700',
    defaultText: 'हे शिव! आप मेरे गुरु हैं, मैं आपका शिष्य हूँ। मुझ पर दया कर दीजिए। 🙏',
    defaultAuthor: '- शिव चर्चा',
    iconName: 'sun',
    artworkUrl: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'st-premium-dark',
    title: 'दिव्य ज्योति (Dark Velvet)',
    category: 'mantra',
    style: 'premium',
    bgGradient: ['#0F172A', '#1E293B'],
    textColor: '#FFFFFF',
    accentColor: '#FF9800',
    defaultText: 'ॐ नमः शिवाय! शिव गुरु की अहैतुकी दया हम सब पर बनी रहे। 📿',
    defaultAuthor: '- 108 जाप साधना',
    iconName: 'flame',
    artworkUrl: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'st-ocean-blue',
    title: 'सोमनाथ नीलम (Ocean Blue)',
    category: 'special',
    style: 'premium',
    bgGradient: ['#0F2027', '#203A43'],
    textColor: '#E0F7FA',
    accentColor: '#4DD0E1',
    defaultText: 'नागेन्द्रहाराय त्रिलोचनाय भस्माङ्गरागाय महेश्वराय... ॐ नमः शिवाय 🔱',
    defaultAuthor: '- शिव पंचाक्षर स्तोत्रम्',
    iconName: 'water',
    artworkUrl: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'st-morning-ivory',
    title: 'शुभ प्रभात (Gold Ivory)',
    category: 'morning',
    style: 'special_day',
    bgGradient: ['#FFF8E7', '#F5E6C8'],
    textColor: '#3E2723',
    accentColor: '#D84315',
    defaultText: 'शुभ प्रभात! आज का दिन शिव गुरु के नाम। ॐ नमः शिवाय 🙏',
    defaultAuthor: '- आज का संदेश',
    iconName: 'sunrise',
    artworkUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=800&auto=format&fit=crop',
  },
];
