import { ShareTemplate } from '../types';

export const shareTemplates: ShareTemplate[] = [
  {
    id: 'st-saffron-classic',
    title: 'पावन केसरिया (Minimal)',
    category: 'daily',
    style: 'minimal',
    bgGradient: ['#E65100', '#BF360C'],
    textColor: '#FFFFFF',
    accentColor: '#FFD700',
    defaultText: 'हे शिव! आप मेरे गुरु हैं, मैं आपका शिष्य हूँ। मुझ पर दया कर दीजिए। 🙏',
    defaultAuthor: '— शिव चर्चा',
    iconName: 'sun',
  },
  {
    id: 'st-maroon-gold',
    title: 'शाही मरून (Traditional)',
    category: 'shiv_guru',
    style: 'traditional',
    bgGradient: ['#4A0E17', '#260408'],
    textColor: '#FFFDF7',
    accentColor: '#F5D061',
    borderStyle: 'gold_ornate',
    defaultText: 'शिव ही गुरु हैं, गुरु ही शिव हैं। आओ चलें शिव की ओर! 🌺',
    defaultAuthor: '— साहब श्री हरिंद्रानंद जी',
    iconName: 'sparkles',
  },
  {
    id: 'st-premium-dark',
    title: 'दिव्य ज्योति (Premium Modern)',
    category: 'mantra',
    style: 'premium',
    bgGradient: ['#1A0006', '#4A0E17'],
    textColor: '#FFFFFF',
    accentColor: '#FF6F00',
    defaultText: 'ॐ नमः शिवाय! शिव गुरु की अहैतुकी दया हम सब पर बनी रहे। 📿',
    defaultAuthor: '— 108 जाप सिद्धी',
    iconName: 'flame',
  },
  {
    id: 'st-morning-ivory',
    title: 'शुभ प्रभात (Morning)',
    category: 'morning',
    style: 'special_day',
    bgGradient: ['#FFF8E7', '#FFE0B2'],
    textColor: '#4A0E17',
    accentColor: '#E65100',
    defaultText: 'शुभ प्रभात! आज का दिन शिव गुरु के नाम। ॐ नमः शिवाय 🙏',
    defaultAuthor: '— आज का संदेश',
    iconName: 'sunrise',
  },
  {
    id: 'st-personal-shishya',
    title: 'व्यक्तिगत कार्ड (Personalized)',
    category: 'personal',
    style: 'personal',
    bgGradient: ['#6A1B29', '#E65100'],
    textColor: '#FFFDF7',
    accentColor: '#FFD700',
    defaultText: 'मैं शिव गुरु की शरण में हूँ। दया, चर्चा और 108 जाप से अपना जीवन धन्य करें।',
    defaultAuthor: '— आपका नाम',
    iconName: 'user',
  },
];
