import { WallpaperItem } from '../types';

export const wallpapersData: WallpaperItem[] = [
  {
    id: 'wp-01-alpine-shrine',
    title: 'हिमालयी स्वर्ण प्रभात मंदिर',
    category: 'himalaya',
    imageIndex: 0,
    description: 'हिमालय की पावन चोटियों पर स्वर्ण सूर्योदय और अलौकिक शिवालय दर्शन।',
  },
  {
    id: 'wp-02-bhasma-ritual',
    title: 'भस्म आरती एवं पावन रुद्राभिषेक',
    category: 'jyotirlinga',
    imageIndex: 1,
    description: 'महाकाल भस्म आरती व दिव्य रुद्राक्ष अर्पित शिव लिंग दर्शन।',
  },
  {
    id: 'wp-03-lotus-shrine',
    title: 'कमल पुष्प अर्पित दिव्य शिवलिंग',
    category: 'swaroop',
    imageIndex: 2,
    description: 'रक्त कमल व बेलपत्र से सुसज्जित दिव्य शिव मंदिर अलौकिक दृश्य।',
  },
  {
    id: 'wp-04-cosmic-sky',
    title: 'अलौकिक नीलकंठ शिव स्वरूप',
    category: 'swaroop',
    imageIndex: 3,
    description: 'अनंत आकाश के तले भगवान शिव का ध्यानस्थ शांत व तेजोमय रूप।',
  },
  {
    id: 'wp-05-cosmic-stars',
    title: 'अनंत ब्रह्मांड एवं महाकाल दर्शन',
    category: 'swaroop',
    imageIndex: 4,
    description: 'तारामंडल एवं कॉस्मिक आकाश में महादेव का विराट तांडव स्वरूप।',
  },
  {
    id: 'wp-06-crescent-moon',
    title: 'चंद्रमौली त्रिशूल एवं डमरू',
    category: 'mantra',
    imageIndex: 5,
    description: 'बालचंद्रधारी शिव का पावन त्रिशूल व डमरू कलात्मक वॉलपेपर।',
  },
  {
    id: 'wp-07-ganga-aarti',
    title: 'काशी पावन गंगा महा आरती',
    category: 'jyotirlinga',
    imageIndex: 6,
    description: 'वाराणसी घाट पर दीपों व शंख ध्वनि से सुशोभित गंगा आरती का दृश्य।',
  },
  {
    id: 'wp-08-himalayan-sunrise',
    title: 'हिमालय सूर्योदय एवं दिव्य त्रिशूल',
    category: 'himalaya',
    imageIndex: 7,
    description: 'कैलाश पर्वत शिखरों पर चमकता स्वर्ण त्रिशूल व प्रभात किरणें।',
  },
  {
    id: 'wp-09-himalayan-moon',
    title: 'सोमनाथ चंद्रलोक एवं शिव ध्यान',
    category: 'himalaya',
    imageIndex: 8,
    description: 'पूर्णिमा की धवल चाँदनी में ध्यानमग्न देवाधिदेव महादेव।',
  },
  {
    id: 'wp-10-dhyan-linga',
    title: 'ध्यानलिंग तपस्या एवं शांति',
    category: 'swaroop',
    imageIndex: 9,
    description: 'अखंड योग निद्रा व ध्यान साधना में लीन परब्रह्म शिव।',
  },
  {
    id: 'wp-11-mystic-damru',
    title: 'पावन डमरू नाद एवं चंद्रमौली',
    category: 'mantra',
    imageIndex: 10,
    description: 'ॐ नमः शिवाय नाद उत्पन्न करता अलौकिक डमरू व शशांक।',
  },
  {
    id: 'wp-12-sadhu-meditation',
    title: 'हिमालय योगी शिव साधना',
    category: 'himalaya',
    imageIndex: 11,
    description: 'तुषार आच्छादित शिखरों पर साधु एकांत शिव आराधना।',
  },
  {
    id: 'wp-13-frozen-shrine',
    title: 'अमरनाथ बर्फानी बाबा पावन गुफा',
    category: 'himalaya',
    imageIndex: 12,
    description: 'श्री अमरनाथ बर्फानी धाम की पवित्र बर्फ आच्छादित घाटी।',
  },
  {
    id: 'wp-14-rudraksha-mala',
    title: 'सिद्धि रुद्राक्ष माला एवं शिव वेदी',
    category: 'mantra',
    imageIndex: 13,
    description: '108 मणके पंचमुखी रुद्राक्ष माला व चंदन लेपित शिव वेदी।',
  },
  {
    id: 'wp-15-sacred-abhisheka',
    title: 'द्वादश ज्योतिर्लिंग जलाभिषेक',
    category: 'jyotirlinga',
    imageIndex: 14,
    description: 'गंगाजल व दुग्धधारा से पूजित ज्योतिर्लिंग पावन दृश्य।',
  },
  {
    id: 'wp-16-shiva-parvati',
    title: 'उमा महेश्वर दिव्य युगल रूप',
    category: 'swaroop',
    imageIndex: 15,
    description: 'भगवान शिव व माता पार्वती का अलौकिक कल्याणकारी रूप।',
  },
  {
    id: 'wp-17-nataraja-fire',
    title: 'आनंद तांडव नटराज स्वरूप',
    category: 'swaroop',
    imageIndex: 16,
    description: 'अग्नि चक्र के मध्य भगवान नटराज का दिव्य नृत्य।',
  },
  {
    id: 'wp-18-snowy-temple',
    title: 'केदारनाथ धाम संध्या आरती',
    category: 'jyotirlinga',
    imageIndex: 17,
    description: 'द्वादश ज्योतिर्लिंग श्री केदारनाथ धाम का पावन संध्याकाल दृश्य।',
  },
  {
    id: 'wp-19-somnath-sunset',
    title: 'प्रथम ज्योतिर्लिंग सोमनाथ सूर्यास्त',
    category: 'jyotirlinga',
    imageIndex: 18,
    description: 'अरब सागर तट पर स्थित प्रथम ज्योतिर्लिंग सोमनाथ मंदिर।',
  },
  {
    id: 'wp-20-twilight-ghats',
    title: 'हरिद्वार हर की पौड़ी दीपदान',
    category: 'jyotirlinga',
    imageIndex: 19,
    description: 'संध्याकालीन पावन गंगा तट एवं जगमगाते घाट का अलौकिक दृश्य।',
  },
];
